### ISSUE TITLE
More simple example?

### ISSUE THREAD

**Issue by viperscape** [syoyo/tinygltf#108]
I cannot figure out how to use this to draw models. Is it possible to have a more simple example, I'm finding the glview example is difficult to follow.
As an example I have so far a basic work in progress https://gist.github.com/viperscape/989cf91ecbd42a2dd89780e30a166c0a
I think my drawMesh is to blame: https://gist.github.com/viperscape/989cf91ecbd42a2dd89780e30a166c0a#file-main-cpp-L88

I was able to render a triangle of vertex points using the same shader and model-view functions. So I must be missing something inherent with how gltf works and how the example was laid out.

Any help is appreciated! If this is too off-topic for an issue, feel free to close

**Comment by viperscape** [comment]
Oh and example of DrawArrays for gltf models would be good, see https://github.com/syoyo/tinygltf/blob/16fae080f99c176db5edc35563a95a1941a37536/examples/glview/glview.cc#L252-L255
I'm finding the Khronos Avocado model is like this.

**Comment by syoyo** [comment]
SaschaWillems' Vulkan-glTF-PBR has mostly full implementation of drawing glTF model on top of TinyGLTF.
Although this is written for Vulkan, but will be useful for OpenGL also.

https://github.com/SaschaWillems/Vulkan-glTF-PBR

Also, improving example is always welcome! Please send PR if you got success to draw more glTF models.

**Comment by viperscape** [comment]
Coming back around to this, I finally figured it all out and have the model rendering with normals. Once I get textures figured out I'm going to create a PR with a VS solution, I think it will be beneficial to have this second example as it uses modern open gl and also removes the need to track vbos and attributes. It looks much like the gist I posted, but is actually working 😁
Thanks and feel free to close this

**Comment by viperscape** [comment]
Got it, closing this issue, see PR https://github.com/syoyo/tinygltf/pull/111
