### ISSUE TITLE
Populating a Model with 3D points Example

### ISSUE THREAD

**Issue by SalehChoueib** [syoyo/tinygltf#113]
Hello, 

   I am in the process of creating a glTF exporter. However I am having some trouble with populating a tinyglTF model with vertex data. I was wondering if anyone has a simple example of creating a model and then populating it with 3D vector data to then be written to a glTF file. 

Thank you.

**Comment by syoyo** [comment]
There is hair(line segment vertices + indices) extension example

https://github.com/syoyo/tinygltfloader/tree/master/examples/cyhair_to_gltf 

Although current glTF 2.0 spec does not support primitives other than polygon, you can do similar technique to export required data as an `extension` or `extras`

**Comment by SalehChoueib** [comment]
Ah, sorry, I may have used inaccurate wording in my question. I did not mean 3D vector data. What I meant was polygon mesh data. I am trying to create a gltf from scratch by populating tinygltf::model and writing it out via WriteGltfSceneToFile(). I am having difficulty taking the points I get from my polygon mesh and storing it in the model->buffer. Is it possible to do this?

**Comment by syoyo** [comment]
glTF itself is a JSON. If you are working your own C++ 3D app and do not require various glTF features, I recommend to write your own exporter with JSON library(e.g. nlohmann's json.hpp, picojosn)

Here is an example to generate old glTF 1.0 JSON using picojson.
https://github.com/syoyo/tinygltfloader/blob/master/examples/cyhair_to_gltf/cyhair2gltf.cc

**Comment by SalehChoueib** [comment]
Ah thank you for the response! I just have one last question. In the specs(https://github.com/KhronosGroup/glTF/tree/master/specification/2.0), it says buffers are required to have a byteLength attribute.

![image](https://user-images.githubusercontent.com/33268561/50106866-085b4c00-01ff-11e9-8fc7-49447868978b.png)
 

I was wondering how tinyGLTF handles this.

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/blob/master/tiny_gltf.h#L2517

**Comment by SalehChoueib** [comment]
Hello,

I apologize, I don't quite understand the answer. Could you please elaborate further?

**Comment by syoyo** [comment]
You are first better study OpenGL and glTF.
