### ISSUE TITLE
Error: Only one of `bufferView` or `uri` should be defined

### ISSUE THREAD

**Issue by viperscape** [syoyo/tinygltf#114]
The latest Khronos exporter for Blender exports both the bufferview and uri for images, tinygltf doesn't seem to like this: ```ERR: Only one of `bufferView` or `uri` should be defined, but both are defined for Image.```
Below is a snippet of the gltf file created
```json
"images" : [
        {
            "bufferView" : 5,
            "mimeType" : "image/png",
            "name" : "rock-mat_normal.bmp",
            "uri" : "rock-mat_normal.png"
        },
        {
            "bufferView" : 6,
            "mimeType" : "image/png",
            "name" : "rock-mat_diffuseOriginal.bmp",
            "uri" : "rock-mat_diffuseOriginal.png"
        },
        {
            "bufferView" : 7,
            "mimeType" : "image/png",
            "name" : "rock-mat_orm.png",
            "uri" : "rock-mat_ormrock-mat_orm.png"
        }
    ],
```

**Comment by syoyo** [comment]
According to glTF schema, 

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/image.schema.json

Only one of bufferView or uri must be defined. You'll get similar error when you pass this glTF file to gltf-validator.

Thus, this is an issue of Blender glTF exporter.

**Comment by viperscape** [comment]
ah I see thanks, I'll post a bug report with Khronos team

**Comment by viperscape** [comment]
Well I'm trying to get the binary loader to work with the binary exported file and it's not happy either, but the file looks good in another gltf viewer with no validation errors. I'm going to open another issue here I think once I figure out what's going on

**Comment by syoyo** [comment]
I see. If you open an issue, please also attach minimal reproducable .glb file >  I'm going to open another issue here I think once I figure out what's going on

**Comment by viperscape** [comment]
Yes so the gltf produced in the new exporter looks like it has a bug where it still packs the image, and includes the bufferviews for each image, and still includes the uri; I posted that on khronos' issue list as it's not a valid file like you mentioned. 
The glb binary file (all in one) is fully validated and looks fine, but unfortunately now I need to implement the draw-arrays, as I [noted here](https://github.com/syoyo/tinygltf/blob/master/examples/basic/main.cpp#L49). Once I figure that out I'll include this latest glb file and update that example to show both ways to load the file

**Comment by viperscape** [comment]
Okay so I'm wrapping my head around this.
bufferView.target ends up being one of three: the GL enum for arrays and elements buffer, or 0; I'm not sure why it's ever 0, but it's 0 with this binary file. If I bind this as such:
```c++
if (bufferView.target == 0)
{
    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, bufferView.byteLength,
        &buffer.data.at(0) + bufferView.byteOffset, GL_STATIC_DRAW);
}
else
{
    glBindBuffer(bufferView.target, vbo);
    glBufferData(bufferView.target, bufferView.byteLength, 
        &buffer.data.at(0) + bufferView.byteOffset, GL_STATIC_DRAW);
}
```
I can draw it as such, where primitive mode is 4 regardless and mesh is triangulated:
```c++
tinygltf::Accessor indexAccessor = this->model.accessors[primitive.indices];
if (this->has_indices)
{
    glDrawElements(primitive.mode, indexAccessor.count, indexAccessor.componentType,
    BUFFER_OFFSET(indexAccessor.byteOffset));
}
else
{
    glDrawArrays(primitive.mode, indexAccessor.byteOffset, indexAccessor.count);
}
```

While it draws, it's not accurate (missing triangles), other draw modes do not work either. So I read the spec and it states this: 

> In glTF, meshes are defined as arrays of primitives. Primitives correspond to the data required for GPU draw calls. Primitives specify one or more attributes, corresponding to the vertex attributes used in the draw calls. Indexed primitives also define an indices property. 
Attributes and indices are defined as references to accessors containing corresponding data. Each primitive also specifies a material and a primitive type that corresponds to the GPU primitive type (e.g., triangle set).
Implementation note: Splitting one mesh into primitives could be useful to limit number of indices per draw call.

> Each primitive corresponds to one WebGL draw call (engines are, of course, free to batch draw calls). 
When a primitive's indices property is defined, it references the accessor to use for index data, and GL's drawElements function should be used. 
When the indices property is not defined, GL's drawArrays function should be used with a count equal to the count property of any of the accessors referenced by the attributes property (they are all equal for a given primitive).


For this mesh, the `indices` in the primitive is 4, while other gltf meshes I've looked at are 0, even though I render them with drawElements. I'm confused on this part.


[rock.zip](https://github.com/syoyo/tinygltf/files/2645160/rock.zip)
See rock.glb (inside the zip)
