### ISSUE TITLE
Bufferview target error, zero when it should be element array enum

### ISSUE THREAD

**Issue by viperscape** [syoyo/tinygltf#116]
Given the spec: https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/schema/mesh.primitive.schema.json
> Primitive Indices: "The index of the accessor that contains mesh indices.  When this is not defined, the primitives should be rendered without indices using `drawArrays()`.  When defined, the accessor must contain indices: the `bufferView` referenced by the accessor should have a `target` equal to 34963 (ELEMENT_ARRAY_BUFFER); `componentType` must be 5121 (UNSIGNED_BYTE), 5123 (UNSIGNED_SHORT) or 5125 (UNSIGNED_INT), the latter may require enabling additional hardware support; `type` must be `\"SCALAR\"`. For triangle primitives, the front face has a counter-clockwise (CCW) winding order."

The loader states that some gltf files have mesh primitives with a bufferview.target of 0, however see attached rock.gltf file, it states indices of 4, which means the target should be 34963. From the spec, unless I'm misunderstanding it, states that the target should only ever be 34963 or 34962 (when indices is missing). Another example is the Khronos avocado gltf2.0 example mesh

[rock.zip](https://github.com/syoyo/tinygltf/files/2649745/rock.zip)

**Comment by viperscape** [comment]
Just to add to this, forcing the target to be Element Array Buffer renders the mesh properly.
```c++
int target = bufferView.target == 0 ? GL_ELEMENT_ARRAY_BUFFER : bufferView.target;
glBindBuffer(target, vbo);
glBufferData(target, bufferView.byteLength,
    &buffer.data.at(0) + bufferView.byteOffset, GL_STATIC_DRAW);
```
So the problem lies specifically with the parser for 'target', I think, as the buffers are fine

**Comment by syoyo** [comment]
Thanks!

Even though it looks the spec does not state **default** `target` value, it looks its safe to initialize it as 34963 (ELEMENT_ARRAY_BUFFER)

> Just to add to this, forcing the target to be Element Array Buffer renders the mesh properly.

You can send a PR!

**Comment by syoyo** [comment]
I thinks this issue is ready to close thanks to the merge of https://github.com/syoyo/tinygltf/pull/117

**Comment by viperscape** [comment]
Yes thanks, just saw this. Looks like after the recent merge, everything is fine
