### ISSUE TITLE
tinygltf for writing out glTF files

### ISSUE THREAD

**Issue by nyue** [syoyo/tinygltf#120]
Hi,

  Before I start writing code, can I clarify that the design purpose of tinygltf is for loading glTF files. Is it designed for writing out glTF files ? If so, which example should I reference to start learning ? If not, what library would you recommend I start looking at for writing out confirming glTF files.

Cheers

**Comment by nyue** [comment]
Answering my own question.

There are methods like Write*() for serializing out.

Cheers

**Comment by syoyo** [comment]
I think @Selmar have some insight or example code how to serialize glTF data using TinyGLTF serializer.

**Comment by Selmar** [comment]
Works just fine for us, but all we're doing is reading files, changing them here and there and writing them back to disk. I don't know what your intention is, but if it is the same, then I guess that will do.

On the other hand, building a glTF from scratch and/or modifying buffer data may prove quite challenging.
