### ISSUE TITLE
accessor.name - should it have a valid string

### ISSUE THREAD

**Issue by nyue** [syoyo/tinygltf#121]
I tried printing out the accessor.name attribute but it seems to be empty string. Is that an expected result ?

I see from the glview example that it->first has been use to reference the name but trying to understand the relationship between it->first and accessor.name

  for (; it != itEnd; it++) {
    const tinygltf::Accessor &accessor = model.accessors[it->second];
    std::cout << boost::format("accessor.name = '%1%' accessor.type = %2% size = %3%") % accessor.name % accessor.type % size << std::endl;
  }

Cheers

**Comment by syoyo** [comment]
`accessor.name` is optional. 

https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/schema/accessor.schema.json

> I see from the glview example that it->first has been use to reference the name 

Do you mean this line?

https://github.com/syoyo/tinygltf/blob/master/examples/glview/glview.cc#L555

In this case `it` is Attributes, not Accessor.
