### ISSUE TITLE
Add TINYGLTF_NO_EXTERNAL_IMAGE to the compiler options on the README

### ISSUE THREAD

**Issue by LouisChildArm** [syoyo/tinygltf#123]
Hi,

This is the first time I've submitted an issue ticket, so I apoligise if I missed something. Anyway, as the title says, I feel like TINYGLTF_NO_EXTERNAL_IMAGE should be added to the README under compiler options. As far as I can tell it doesn't seem to be properly documented anywhere and it actually proves a very useful tool at least for my use case

Thanks

**Comment by syoyo** [comment]
Thanks! I have added document on `TINYGLTF_NO_EXTERNAL_IMAGE`

**Comment by LouisChildArm** [comment]
Cool, thanks :D
