### ISSUE TITLE
Interface for accessing material extension properties

### ISSUE THREAD

**Issue by SaschaWillems** [syoyo/tinygltf#126]
After updating to a recent version of the loader I'm having a hard time getting properties from material extensions, mainly for the specular glossiness workflow.

Wit the old loader I could simply access these values using the ```extPBRValues``` member of a material but that doesn't seem to be available anymore.

So the only way I found for accessing material extension properties seems to be through the ```Value``` type, but this is giving me a hard time esp. on vectors, as the array members of such a vector may end up with different types.

Take e.g. this material definition:

![image](https://user-images.githubusercontent.com/10283127/50421667-50ebb880-0842-11e9-9e11-7dec1ab2be63.png)

Note the ```diffuseFactor```, which in this case is [0, 0, 0, 0.7].

Accessing this via the Value interface gives me a mix of number and int typed array values:

![image](https://user-images.githubusercontent.com/10283127/50421676-6fea4a80-0842-11e9-833b-0656aef0cde2.png)

Taking this into account makes up for some messy code like this:

![image](https://user-images.githubusercontent.com/10283127/50421719-cc4d6a00-0842-11e9-9f22-d2395b306e49.png)

Is there a more convenient way of accessing these? If not, would it be possible to add a more natural interface for accessing such values. The ```extPBRValues``` interface was nice, but I guess it was too limited and as such had to be replaced with something more generic, but writing code like the above doesn't feel right somehow.

**Comment by syoyo** [comment]
I don't remember why `extPBRValues`  disappeared but I guess it was done when picojson -> nlohmann json.hpp transition.

For the moment, we need to write a wrapper function to parse Value like this:

```
static bool GetColorFactor(const tinygltf::Value &value, float result[3]) {
  int valid = 0;
  float color[3] = {0.0f, 0.0f, 0.0f};

  if (value.IsArray()) {
    if (value.Size() == 3) {
      for (int i = 0; i < 3; i++) {
        if (value.Get(i).IsNumber()) {
          color[i] = float(value.Get(i).Get<double>());
          valid++;
        } else if (value.Get(i).IsInt()) {
          // probably 0 or 1.
          color[i] = float(value.Get(i).Get<int>());
          valid++;
        }
      }
    }
  }
  if (valid == 3) {
    result[0] = color[0];
    result[1] = color[1];
    result[2] = color[2];

    return true;
  }

  return false;
}

bool ParsePBRMaterial(const tinygltf::Value &pbr_material_params,
                      Material &loadedMaterial /* inout */) {
  if (!pbr_material_params.IsObject()) {
    return false;
  }

  const tinygltf::Value::Object &o =
      pbr_material_params.Get<tinygltf::Value::Object>();
  tinygltf::Value::Object::const_iterator itr(o.begin());
  tinygltf::Value::Object::const_iterator itrEnd(o.end());

  for (; itr != itrEnd; itr++) {
    const std::string &key = itr->first;
    const tinygltf::Value param = itr->second;
    if (key.compare("baseColor") == 0) {
      float color[3];
      if (GetColorFactor(param, color)) {
        loadedMaterial.diffuse[0] = color[0];
        loadedMaterial.diffuse[1] = color[1];
        loadedMaterial.diffuse[2] = color[2];
      }
  ...
```

And here is another example for parsing texture index:

https://github.com/lighttransport/nanort/blob/master/examples/pbr_surface/gltf-loader.cc#L462


`KHR_materials_pbrSpecularGlossiness` is now official 2.0 glTF extension,

https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness

thus at least it is handy to provide predefined parser & data structure  for `KHR_materials_pbrSpecularGlossiness` . PR is always welcome!

**Comment by syoyo** [comment]
KHR material extensions are now reconstructed as an explicit struct:  https://github.com/syoyo/tinygltf/tree/KHR_material_firstcitizen

@SaschaWillems Please try this branch: https://github.com/syoyo/tinygltf/tree/KHR_material_firstcitizen 

Although you still need to parse other extensions from opaque `Value` class.

**Comment by syoyo** [comment]
Now original JSON string can be exposed using `SetStoreOriginalJSONForExtrasAndExtensions` method.

https://github.com/syoyo/tinygltf/pull/217

You'll have `std::string` representation of `extras` and `extensions` for each glTF object.

For example, you can use spotify-json or StaticJSON to easily reconstruct C++ struct from JSON string.

https://github.com/spotify/spotify-json

https://github.com/netheril96/StaticJSON
