### ISSUE TITLE
Include file problem

### ISSUE THREAD

**Issue by nyue** [syoyo/tinygltf#130]
I splitting up my program into libraries as part of refactoring.

In my monolithic example, I have a single block

#define TINYGLTF_IMPLEMENTATION                                                                                                              
#define STB_IMAGE_IMPLEMENTATION                                                                                                             
#define STB_IMAGE_WRITE_IMPLEMENTATION                                                                                                       
#include <tiny_gltf.h>      

During refactoring, I needed to create different header file for different parts which deals with gltf content in different ways. In those header files, I also have the above block.

I noticed that once I have more than one of the above, I start getting compiler errors about stbi__err

What is the correct way to include tiny_gltf.h multiple times ?

Cheers

**Comment by syoyo** [comment]
Implementation(`TINYGLTF_IMPLEMENTATION`) must be defined in only single .cc file, as noted here:

https://github.com/syoyo/tinygltf#loading-gltf-20-model
