### ISSUE TITLE
Garbled buffers and animations using Draco compressed meshes

### ISSUE THREAD

**Issue by SaschaWillems** [syoyo/tinygltf#135]
I was playing around with the recently added @abwood Draco compression in my Vulkan C++ PBR demo and while some of the draco compressed gltf sample meshes worked fine, I noticed that on some buffer output is garbled and animations no longer seem to work as expected.

Two examples:
![image](https://user-images.githubusercontent.com/10283127/51785814-0371ac80-215c-11e9-8bc4-6c87375060ae.png)
![image](https://user-images.githubusercontent.com/10283127/51785815-066c9d00-215c-11e9-8b85-4fb4e99c15ca.png)

Animations e.g. no longer work with the BrainSteam model. Instead of it dancing as expected (working fine with non-compressed versions) it just statically rotates around a single axis.

I guess the Draco implementation is not fully finished yet, so I just wanted to let you know of some of the problems I've encountered.

The Draco library used for testing was built from the latest sources at https://github.com/google/draco.

I'm still figuring out how to easily add Draco to the builds for my sample, and will push a new branch that could be used to test Draco decompression with tinygltf.

**Comment by abwood** [comment]
Yes, there remains a few more items that need to be added before merging, namely adding draco as an optional submodule, cmake updates, and unit testing.  Community testing is much appreciated along the way.

In my application, I'm seeing the draco Buggy.gltf (model in top screenshot) render correctly with draco compression.  I'm building your sample project locally and I'll see if I can track down any discrepancies.

**Comment by abwood** [comment]
![image](https://user-images.githubusercontent.com/3868547/51787572-cb5d7000-2141-11e9-8de0-f7c9950bac05.png)

Found the issue!

**Comment by abwood** [comment]
Draco decoder is optimizing the mesh and has discarded some faces.  The accessor.count property was not reassigned after decoding.  I'll setup a PR shortly.

**Comment by abwood** [comment]
Animations were a separate issue that I have now resolved too.  Draco reported the componentType of the Joint attributes as float32, but the componentType on the accessor in gltf indicates that the underlying componentType should be unsigned short.  I've updated the tiny_gltf decode to extract the attributes based on the expected componentType defined on the accessor.

**Comment by SaschaWillems** [comment]
Thx for the quick response and fixing this :)

The draco compressed models from the glTF sample repository now all render and animate as supposed.

Awesome job 👍

**Comment by syoyo** [comment]
I have also confirmed some Draco compressed glTF model works well in `examples/glview` example, so merged into `master`
