### ISSUE TITLE
Impossible to get camera information ?

### ISSUE THREAD

**Issue by newincpp** [syoyo/tinygltf#14]
As far As I understand the tiny_gltf I should use the camera index Node::camera and use it to find the good camera in corresponding std::vector in tinygltf::Model.

The problem is there is no std::vector<Camera> in Model, grep -i "Camera" only give me the class definition of Camera and there is no reference to camera loading in the examples that I could find.

On my engine I will assume that the camera position/rotation is the node position/rotation but I can't get more information from the node (fov, aspect ratio, zfar/znear etc...)

Did I missed something or it isn't implemented ?

**Comment by syoyo** [comment]
Camera feature is not yet implemented.

Do you have a sample glTF model for testing Camera node?

**Comment by syoyo** [comment]
Added initial support for parsing `Camera` in this commit: https://github.com/syoyo/tinygltf/commit/7b6edab3a9c2589b7af00d2c2c88584bb2e7788c

**Comment by newincpp** [comment]
You can find the files I'm trying to load using tinygltf here:
tiny scene 1 camera: github.com/newincpp/LunaticPlatypus/blob/master/demo/nelo.gltf
medium scene 1 camera binary: github.com/newincpp/LunaticPlatypus/blob/master/demo/sponza.glb
medium scene multiple camera: github.com/newincpp/LunaticPlatypus/blob/master/demo/vega.gltf
All those files are made by me using blender and the exported using the Khronos github plugin.

**Comment by syoyo** [comment]
I run `loader_example` for nelo.gltf, sponza.glb and vega.gltf and looks now Camera node is parsed correctly.

**Comment by newincpp** [comment]
I just pulled and tested and this looks fine for me too. Thanks for reacting that fast

**Comment by syoyo** [comment]
Thanks!

**Comment by DaviesX** [comment]
I wonder where can I find the transformation information of a camera?

**Comment by Ybalrid** [comment]
@DaviesX If the camera is part of a scene in a glTF asset, it will be attached to a node. A scene is a graph made up of nodes attached together.

You'll find that a camera is attached to a `node` that is part of a `scene`. each node has a local `transform` that is relative to it's parent one.

If you want the world space transform of a camera, you need to multiply together the transformation matrices of the nodes from the root of the scene.

tinygltf directly exposes you the parsed `scenes` and `nodes` array. Every reference to another object is expressed as a `int` that is the index of an object in it's respective array.

**Comment by DaviesX** [comment]
@Ybalrid Thanks for your quick reply. Then, I wonder how do I obtain this node attachment relationship? 

My guess is I should look into the field gltf::Node::camera for each node in gltf::Model::scenes as well as in their respective sub-trees. In particular, when this field has value of k >= 0, it's referencing the k-th camera in the vector gltf::Model::cameras. 

Am I heading towards the right direction?

**Comment by Ybalrid** [comment]
@DaviesX I'm happy to help! ^^"

Yes, that's how it works. The node simply contains the index in that array of camera. 

As you can see, once loaded by the library, every single "kind" of object in the gltf asset is stored in a respective vector inside the tinygltf "model" object : accessors, messhes, buffers, cameras...

These objects point to each other using the index in their respective vectors.

Here's how the relationship between objects works inside a glTF asset:

![image](https://user-images.githubusercontent.com/1816251/54519438-d32dd980-4966-11e9-8908-700883856d9d.png)

This picture is from the "poster" that is a summary of the glTF specification, from here : https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/gltfOverview-2.0.0b.png

**Comment by DaviesX** [comment]
I see. Thank you again @Ybalrid
