### ISSUE TITLE
Use rapidjson as a JSON library

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinygltf#141]
Currently TinyGLTF uses nlohmann's json.hpp https://github.com/nlohmann/json as an underlying JSON library.

json.hpp is working well, but is overkill for TinyGLTF and sometimes it faces the portability problem related to C++ compiler versions.

https://github.com/dropbox/json11 is much more simple, portable, and has enough feature for TinyGLTF. I have implemented json11 version of TinyGLTF in `json11` branch: https://github.com/syoyo/tinygltf/tree/json11

I am planning to switch to use json11 after running several tests.

**Comment by meshula** [comment]
You might want to check timings. nlohmann json is not that fast, but it's faster than dropbox/json11...

https://github.com/miloyip/nativejson-benchmark

I'm personally using rapidjson, but YMMV of course.

**Comment by syoyo** [comment]
> I'm personally using rapidjson, but YMMV of course.

You can contribute rapidjson version of TinyGLTF. PR is always welcome!
(Selecting JSON library by ifdef would be nice)

**Comment by vinjn** [comment]
Love this change - json.hpp is too huge

**Comment by Ybalrid** [comment]
I tend to agree about RapidJSON being a great choice

**Comment by syoyo** [comment]
I have revisiting rapidjson and found there is a script which can generate single file of rapidjson headers.

https://github.com/Tencent/rapidjson/issues/863


I have wrote rapidjson-amalgamation version of tinygltf(W.I.P.) and it works well so far.

https://github.com/syoyo/tinygltf/tree/rapidjson

It looks promising so I am planning to switch to use rapidjson for faster C++ compilation and builtin support of schema validator.

**Comment by Selmar** [comment]
This will be great for us as well, as we are currently struggling with the # of allocations. Schema validation is an awesome plus! 👍

**Comment by syoyo** [comment]
We can now use RapidJSON in `master` branch by defining `TINYGLTF_USE_RAPIDJSON` and set include path to RapidJSON.
