### ISSUE TITLE
getting vertex buffer from Mesh

### ISSUE THREAD

**Issue by newincpp** [syoyo/tinygltf#15]
Hi,
I'm trying to bind tinygltf to my graphics engine but there something I either don't understand or isn't supported.
According to this spec:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0
I should be able to get the vertex buffer from the Mesh. I was expecting to do something like:
`model->accessors[mesh.primitives[i].BufferViewIndex]`
and then getting the buffer to call `glBufferStorage`/`glBufferData` but the Primitive only contain "indices" and "material".

I cannot just loop through all `model_->bufferViews` because I need to know which bufferView is owned to which mesh.

**Comment by syoyo** [comment]
> I should be able to get the vertex buffer from the Mesh. I was expecting to do something like:
> model->accessors[mesh.primitives[i].BufferViewIndex]

`Primitive` does not have bufferView index or similar item.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#primitive

Please describe what you want to do in more detail.

Also, `examples/glview` sample code would help you to understand how to map `tinygltf` data structure to OpenGL API.

**Comment by newincpp** [comment]
I use glview.cc as a reference to make my implementation but in this file the function "SetupMeshState(tinygltf::Model &model, GLuint progId)" is looping through all BufferView like this:
`for (size_t i = 0; i < model.bufferViews.size(); i++) {`
and just register opengl state like this:
`gBufferState[i] = state`
By doing this I have no way of knowing which Mesh is linked to which BufferView. For some reason I can use Accessor and Primitives I can find the linked GL_ELEMENT_ARRAY_BUFFER (aka indice buffer) but no way of finding the linked GL_ARRAY_BUFFER (aka vertex buffer).

Said another way I can:
`model->accessors[mesh.primitives[i].indices].bufferView` to get one of the index buffer linked to a mesh
but I can't do something like
`model->accesors[mesh.???.vertices].bufferView` to get one of the vertex buffer linked to a mesh.

At this point I'm realising that this is not an issue with tinygltf at all but my understanding of the gltf format.
If I achieve to make it work I think I will write a tutorial...

**Comment by brycehutchings** [comment]
To do it right, you traverse the nodes in the scene that you want to render (there is usually just one scene). Each node contains and optional mesh. Nodes also contain optional transforms which apply to the mesh and descendent nodes. Meshes contain primitive(s). Primitives reference accessors. Accessors reference buffer views. Buffer views reference buffers. Simple :-).

________________________________

**Comment by newincpp** [comment]
That's exactly what I'm trying to do but once I've reached the "mesh" step I can't get any GL_ARRAY_BUFFER.
this code:
```
    for (const tinygltf::Primitive &primitive : mesh_.primitives) {
        const tinygltf::Accessor &indexAccessor = model_->accessors[primitive.indices];
        if (indexAccessor.bufferView != -1) {
            std::cout << "trying to access bufferview " << indexAccessor.bufferView << " in accessor " << primitive.indices << '\n';
            const tinygltf::BufferView &bufferView = model_->bufferViews[indexAccessor.bufferView];
            if (bufferView.target == 0) {
                std::cout << "WARN: bufferView.target is zero" << std::endl;
                continue;  // Unsupported bufferView.
            } else if (bufferView.target == GL_ELEMENT_ARRAY_BUFFER){
                std::cout << "generating GL_ELEMENT_ARRAY_BUFFER\n";
            } else if (bufferView.target == GL_ARRAY_BUFFER){
                std::cout << "generating GL_ARRAY_BUFFER\n";
            }
```
never display "generating GL_ARRAY_BUFFER" and that's the root of all my problems

**Comment by brycehutchings** [comment]
primitive.indices will (optionally) point to index data, not vertex data. You’ll have to look at the primitive’s attributes dictionary (POSITION, NORMAL, etc) to get pointers to the accessor vertex data. The “attributes” name seems too vague for my liking, but it appears to be exclusively _vertex_ attributes. I don’t have an OpenGL background, so the naming may make more sense from that perspective.

**Comment by syoyo** [comment]
> That's exactly what I'm trying to do but once I've reached the "mesh" step I can't get any GL_ARRAY_BUFFER.

As @brycehutchings said, there is no `GL_ARRAY_BUFFER` for index buffer. (optional) index buffer is only bound to `GL_ELEMENT_ARRAY_BUFFER`(Its a bit confusing OpenGL naming, though)

http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-9-vbo-indexing/

**Comment by syoyo** [comment]
> no way of finding the linked GL_ARRAY_BUFFER (aka vertex buffer).

As @brycehutchings also described, you'll need to traverse `mesh.primives.attributes` and figure out which BufferView is bound to an attribute(vertex attribute), e.g. "POSITION".

In `glview.cc` example, name and bufferView index relationship is hardcoded for simplicity.

**Comment by newincpp** [comment]
So If I understand well, to get my vertex positions I have to do something like this:
```
for (const tinygltf::Primitive &primitive : mesh.primitives) {
    for (const std::pair<const std::string, int>& attribute : primitive.attributes) {
        const tinygltf::Accessor &accessor = model_->accessors[attribute.second];
        if ((attribute.first.compare("POSITION") == 0) {
            const tinygltf::Buffer &vertexArray = model_->buffers[model_->bufferViews[accessor.bufferView].buffer]; // Array of vertex Positions
        }
    }
}
```

If this is right my whole problem came from the fact I get confused between what opengl call "attribute" and gltf call "attribute".

**Comment by brycehutchings** [comment]
That looks right. You really need to read the gltf 2.0 spec to use tinygltf correctly and get a decent number of gltf features supported in a renderer.

**Comment by syoyo** [comment]
> what opengl call "attribute" and gltf call "attribute".

As far as I know, opengl "attribute" and gltf "attribute" are same thing.

@newincpp You can send PR if you find any inconsistency between glTF 2.0 spec and `tinygltf`.
