### ISSUE TITLE
static_assert failed "could not find from_json() method in T's namespace" in Xcode 10.2

### ISSUE THREAD

**Issue by AlexPreston906** [syoyo/tinygltf#156]
I get the following error message when compiling my libraries on Xcode 10.2. When compiling on Xcode 10.1 I see no such issue. This specifically comes from your use of json.hpp.

/Users/*username*/Documents/GitHub/*library*/thirdparty/tinygltf/./json.hpp:1378:9: error: static_assert failed "could not find from_json() method in T's namespace"
        static_assert(sizeof(BasicJsonType) == 0,

/Users/*username*/Documents/GitHub/*library*/thirdparty/tinygltf/./json.hpp:1387:16: note: in instantiation of function template specialization 'nlohmann::detail::from_json_fn::call<nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long, double, std::allocator, adl_serializer>, std::__1::basic_string_view<char, std::__1::char_traits<char> > >' requested here
        return call(j, val, priority_tag<1> {});

**Comment by syoyo** [comment]
Please update TinyGltf. You are using old tiny_gltf.

I had encountered similar compilation issue of json.hpp before and fixed it in this commit: https://github.com/syoyo/tinygltf/commit/c0d0251e2c7f2273a894aa1b125af9313a88eae4

I've confirmed XCode 10.2's clang compiles fine with current `master` : https://github.com/syoyo/tinygltf/commit/b3c147131740dad0a49e71d9f698a710480f83e0

```
$ clang++ -v
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ clang++   -std=c++11 -g -O0 -o loader_example loader_example.cc
# ok
```

**Comment by AlexPreston906** [comment]
Updated and code compiles. Thank you!
