### ISSUE TITLE
Inputs to loader_example that cause assert/abort behavior

### ISSUE THREAD

**Issue by rwhitworth** [syoyo/tinygltf#16]
Hi,

I used afl-fuzz (American Fuzzy Lop) to fuzz test input to the loader_example program.  It triggered assertions (abort behavior, I believe to be intentional) but no major issues were found.  I wanted to let you know in case these are worth your time to fix.  If not, then please close this issue at your leasire.

Input files and a few example stack traces can be found here: https://github.com/rwhitworth/tinygltf-fuzz/tree/master/2017-07-31

**Comment by syoyo** [comment]
Cool!

Its definitely worth for hardening tinygltf parser.

I will try to fix it(PR is welcome, though)

**Comment by syoyo** [comment]
I did some fixes into `devel` branch.

Some seg fault happens inside `picojson`(e.g.` id:000062,sig:06,src:000592+000619,op:splice,rep:8`), so I may need to fix `picojson` to pass all fuzzer inputs.

**Comment by syoyo** [comment]
Fixes in recent `devel` branch.

At least now `tinygltf` parsing does not abort anymore for given fuzz inputs. Thanks for running fuzzer and reporting!
