### ISSUE TITLE
Animation sampler interpolation mode in docs doesn't exist in glTF 2.0 specifications

### ISSUE THREAD

**Issue by Ybalrid** [syoyo/tinygltf#166]
Consider the comments here: https://github.com/syoyo/tinygltf/blob/master/tiny_gltf.h#L440

The interpolation mode `CATMULLROMSPLINE` is not part of the glTF specification. By loading a standard glTF the `AnimationSampler::interpolation` string will never be equals to `CATMULLROMSPLINE`.

glTF 2.0 : https://github.com/KhronosGroup/glTF/tree/master/specification/2.0?ts=4#animations (3rd paragraph after the JSON codeblock)

> Interpolation between keys is performed using the `interpolation` method specified in the interpolation property. Supported `interpolation` values include `LINEAR`, `STEP`, and `CUBICSPLINE`

This information should be removed from the list. 

If that interpolation mode is provided by an extension, it should be provided as an extension value anyway...

**Comment by syoyo** [comment]
Thanks! After glimpsed glTF git repo and github issues, `CATMULLROMSPLINE` was exist in glTF 2.0 beta phase(? when I was started to working on parser for glTF 2.0) but removed in the final glTF 2.0 spec.

https://github.com/KhronosGroup/glTF/issues/605#issuecomment-308594711

So, yes, I will remove `CATMULLROMSPLINE` soon.

**Comment by Ybalrid** [comment]
>  exist in glTF 2.0 beta phase

**Comment by Ybalrid** [comment]
> exist in glTF 2.0 beta phase

Okay, so that's why. It's just a comment message anyway, I think tinygltf just pulls the content of the string inside the JSON object.

It's just a matter to keep the comments that serve as documenting the data in accordance to the specification. :slightly_smiling_face:

**Comment by syoyo** [comment]
Removed `https://github.com/syoyo/tinygltf/commit/fbc429577031f29f1fa0a93503ae1438fc8c918e` by this commit: https://github.com/syoyo/tinygltf/commit/fbc429577031f29f1fa0a93503ae1438fc8c918e
