### ISSUE TITLE
trackball.h?

### ISSUE THREAD

**Issue by GeneralJing** [syoyo/tinygltf#167]
where is this file?

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/blob/master/examples/common/trackball.h

**Comment by GeneralJing** [comment]
thank you. I found the trackball.h and trackball.cpp in the apple website. But the render result is just a blank background. I didn't find the reason. when I change the glclear function, the color seens no change. can you give me some advice?
<img width="768" alt="image" src="https://user-images.githubusercontent.com/6658900/57841205-b8f46880-77fc-11e9-8ef6-f63e7cc2528e.png">

**Comment by GeneralJing** [comment]
this is the print output:
Load shader [ shader.vert ] OK
Load shader [ shader.frag ] OK
Link shader OK
0 is used by accessor 0
buffer.size= 1800, byteOffset = 0
1 is used by accessor 1
buffer.size= 1800, byteOffset = 72
2 is used by accessor 2
buffer.size= 1800, byteOffset = 504
3 is used by accessor 3
buffer.size= 1800, byteOffset = 936
4 is used by accessor 4
buffer.size= 1800, byteOffset = 1512
# of meshes = 1
I'm new to gltf, and not familiar with the format. I used to use the .obj model file.

**Comment by syoyo** [comment]
You can drag mouse to change view and you'll see cube

**Comment by GeneralJing** [comment]
thank you very much. now I can see the render result. I think I should change the modelview and projection matrix to see it better.

**Comment by syoyo** [comment]
@GeneralJing  Computing the bounding box of input .obj mesh and calculate a good view position(modelview) to fit entire mesh into viewport is TODO. You can contribute!(please send a PR)

**Comment by Ybalrid** [comment]
@GeneralJing And every primitive in a gltf has a "min" and a "max" vector that can be used to calculate the 8 vertices of a bounding box this way : 

```
{ min.x, min.y, max.z },
{ min.x, max.y, max.z },
{ min.x, max.y, min.z },
{ min.x, min.y, min.z },
{ max.x, min.y, max.z },
{ max.x, max.y, max.z },
{ max.x, max.y, min.z },
{ max.x, min.y, min.z }
```

**Comment by GeneralJing** [comment]
@syoyo @Ybalrid thank you both. In face, I have used the scale variable to scale the display model and it gives a better view. Of course, I will try the method mentioned by you. Thanks again.
