### ISSUE TITLE
glTF texcoord bugs

### ISSUE THREAD

**Issue by ghost** [syoyo/tinygltf#17]
Last time, last updates (after MSVC fix) glTF not loading correctly (texcoords). I also, loading images by FreeImage. Here is model https://sketchfab.com/features/gltf

![gltf-bug](https://user-images.githubusercontent.com/28119043/28814120-ec117b12-76ce-11e7-838e-56bd8b28910d.png)

**Comment by syoyo** [comment]
Please post reproducable dataset and codes.

Also, PR is welcome > after MSVC fix

**Comment by capitalknew** [comment]
In one of old versions
https://github.com/capitalknew/paper-render-2/tree/403a7b627a355a4476ff94613f21b5015cbe1a09

After some devel updates texcoords distortion 
https://github.com/capitalknew/paper-render-2/commit/e17e4eba4df4b51dccfba542f48453e48f5c57fd

**Comment by syoyo** [comment]
I meant minimal reproducable codes.

FYI, can you extend `glview` example to support PBR shader and texturing?

**Comment by capitalknew** [comment]
About PBR, I using Path Tracing for realization, texturing also bindless and I did hard work for make support of texturing.

**Comment by syoyo** [comment]
How about adding PBR and texturing support in `raytrace` example(CPU raytracing of glTF model)?

https://github.com/syoyo/tinygltf/tree/devel/examples/raytrace

Its W.I.P(need to support node hierarcy), but adding PBR/texturing support would be rather easy.

**Comment by capitalknew** [comment]
I have a counter suggestion to join the development of my path tracing. But now the work of sponza has broken down. I also have well-developed support for glTF (so far the animation has not been implemented). Also we already have real-time BVH. Not so long ago, development began under OpenGL 4.6.

https://github.com/capitalknew/paper-render-2

**Comment by Ybalrid** [comment]
Sorry for jumping into the discussion, but to go back to the texture coordinates, It seems to me that the buffer reported by the library contains valid textures coordinates, with the code in the repository today, and that everything is working fine.)

(This is the "Corset" test model from the samples provided on the Khronos repository, here there's just one light on the scene and no environment map to show the full effect of the material, Only the baseColor, metalRough, and normalMap are used in this rendering done with Ogre 2.1)

![macro 5](https://user-images.githubusercontent.com/1816251/34489595-40627a68-efdd-11e7-9690-0ad47a40d6c6.gif)

**Comment by syoyo** [comment]
Awesome @Ybalrid !

>  It seems to me that the buffer reported by the library contains valid textures coordinates,

Thank you for testing `TinyGLTF` with  glTF model with textures. So it looks this issue has been solved.

**Comment by Ybalrid** [comment]
I think the original issue is indeed solved. The discussion on this thread shifted towards implementing a raytracing example and putting the usage of PBR texture there.

If this is something that need to be worked on, the best thing IMO is to close this issue and open a new one explaining this.

Also, it seems that the original author has deleted their GitHub account since...

**Comment by syoyo** [comment]
> I think the original issue is indeed solved. The discussion on this thread shifted towards implementing a raytracing example and putting the usage of PBR texture there.

Thank you for the comment. I'll close this issue and writing PBR texture example will be discussed here: 
 https://github.com/syoyo/tinygltf/issues/4
