### ISSUE TITLE
"Already defined" error when tiny_gltf.h included multiple times.

### ISSUE THREAD

**Issue by SuperWangKai** [syoyo/tinygltf#175]
When we include tiny_gltf.h in different .cpp files, since all the implementations of the functions are in the header, compiler will complain for "already defined" error.

In my example, I included tiny_gltf.h in both `GLTFInfo.cpp` and `GLTFImport.cpp`.

Here is the message from VS 2017:

`1>GLTFInfo.obj : error LNK2005: "bool __cdecl tinygltf::IsDataURI(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?IsDataURI@tinygltf@@YA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) already defined in GLTFImport.obj`

**Comment by syoyo** [comment]
As described in README

https://github.com/syoyo/tinygltf#loading-gltf-20-model

You should define `TINYGLTF_IMPLEMENTATION` in single compilation unit(.cpp)

**Comment by SuperWangKai** [comment]
Thanks. Problem solved.

**Comment by SuperWangKai** [comment]
Is it better if we use `static` or `inline` to avoid the issue without define `TINYGLTF_IMPLEMENTATION`?

**Comment by syoyo** [comment]
> avoid the issue without define TINYGLTF_IMPLEMENTATION?

Defining `***_IMPLEMENTATION` is a commonly known idiom to use header-only library

https://github.com/nothings/stb/blob/master/stb_image.h#L4
