### ISSUE TITLE
minFilter and magFilter in Sampler are set to default values (9987 and 9729)

### ISSUE THREAD

**Issue by UX3D-haertl** [syoyo/tinygltf#186]
Those values don't have a default value specified in the documentation and are not required.
From specification:

> Default Filtering Implementation Note: When filtering options are defined, runtime must use them. Otherwise, it is free to adapt filtering to performance or quality goals.

They could be set to e.g. -1 if not defined.

**Comment by syoyo** [comment]
Thanks! I have chosen setting `-1` as an default value.
