### ISSUE TITLE
serialize material bug

### ISSUE THREAD

**Issue by dytmh** [syoyo/tinygltf#189]
SerializeGltfMaterial
 
if (material.normalTexture.index >= -1) {
    json texinfo;
    SerializeGltfNormalTextureInfo(material.normalTexture, texinfo);
    o["normalTexture"] = texinfo;
  }

  if (material.occlusionTexture.index >= -1) {
    json texinfo;
    SerializeGltfOcclusionTextureInfo(material.occlusionTexture, texinfo);
    o["occlusionTexture"] = texinfo;
  }

  if (material.emissiveTexture.index >= -1) {
    json texinfo;
    SerializeGltfTextureInfo(material.emissiveTexture, texinfo);
    o["emissiveTexture"] = texinfo;
  }

SerializeGltfPbrMetallicRoughness

if (pbr.baseColorTexture.index >= -1) {
    json texinfo;
    SerializeGltfTextureInfo(pbr.baseColorTexture, texinfo);
    o["baseColorTexture"] = texinfo;
  }

  if (pbr.metallicRoughnessTexture.index >= -1) {
    json texinfo;
    SerializeGltfTextureInfo(pbr.metallicRoughnessTexture, texinfo);
    o["metallicRoughnessTexture"] = texinfo;
  }

It should be
if (material.normalTexture.index > -1) 
if (material.occlusionTexture.index > -1) 
if (material.emissiveTexture.index > -1) 
if (pbr.baseColorTexture.index > -1) {
if (pbr.metallicRoughnessTexture.index > -1) {

**Comment by syoyo** [comment]
Thanks! Fixed!
