### ISSUE TITLE
Move Constructors

### ISSUE THREAD

**Issue by jrkoonce** [syoyo/tinygltf#197]
The library often utilizes vectors of user defined structs/classes.  None of those structs/classes are defining move constructors, leaving them to be implicitly generated by the compiler if possible.  From first glance, it appears most of them can be implicitly generated, however, std::vector also has the requirement that the move constructor be declared noexcept before it can be used.

I am not sure implicitly generated move constructors will be noexcept .  The move constructor can be explicitly defined to be the default implementation and noexcept both: "T(T&&) noexcept = default;" This ensures the move constructor can be implicitly generated by the compiler and that it is noexcept, or it won't compile.  As coded now, it will compile and be a silent copy instead of move whenever the non-throwing move constructor can't be generated.

I would add the definition of the defaulted explicit noexcept move constructors, to ensure maximum CPU and memory efficiency, with compile errors indicating when a copy would occur instead of a move.  When a compile error occurs, an explicit noexcept move constructor can be programmed.  Thus ensuring all user defined structs/classes will be correctly moved and not copied inside of std::vector.

**Comment by syoyo** [comment]
tinygltf was initially written for targeting C++03 compiler, and there is no move constructors used in current `master` yet. 

PR of adding wide support of move semantics including move constructor to tinygltf classes is appreciated.

**Comment by jrkoonce** [comment]
I made a fork and have added them. Reduces allocations by a lot. I’ll check it in today and you can integrate it back if you want. It is a pretty quick implementation, so you will want to check it across all compilers and clean it up.

Rusty

**Comment by syoyo** [comment]
Code looks nice. Please create a PR. It will trigger CI build on Linux.

**Comment by jrkoonce** [comment]
Well, I have good news and bad news.  Good news, is I got a lot more move semantics in and I added support for RapidJSON 1.1.  Bad news is I used a C++14 feature (auto parameter to lambda) not realizing you restricted the code to C++11.  I can rewrite the code to not use that feature, but it makes the code much more verbose and long.   The RapidJSON support was rushed and probably could use a bit more cleanup and definitely more testing.

**Comment by syoyo** [comment]
Awesome! > RapidJSON support.

>  I used a C++14 feature (auto parameter to lambda) not realizing you restricted the code to C++11

We still need to stick with C++11. Could you rewrite the code in C++11?
(We may switch to use C++14 in the future release(and it will bump the major version(i.e. v3.x))

**Comment by jrkoonce** [comment]
Yes I will do that. I’m traveling over this holiday weekend but will take out the C++14 when I get back.

**Comment by syoyo** [comment]
PR has been merged https://github.com/syoyo/tinygltf/pull/201

So this issue should be ready to close.

**Comment by Selmar** [comment]
Question: why did we end up with a custom move constructor implementation? It was not possible to mark the default move constructor noexcept, i.e. `T(T&&) noexcept = default;` like you initially suggested?

The current implementation is very error-prone (managing operator== is already a pain).

**Comment by syoyo** [comment]
> The current implementation is very error-prone (managing operator== is already a pain).

I have less knowledge on C++11 move semantics. What is the preferred way(or best practice) of move semantics(and `operator==`) for TinyGLTF code?

**Comment by jrkoonce** [comment]
Good question.  The compiler complained about implementing the default. I don’t remember what was setting it off. If you have a custom destructor, custom copy constructor, or several other things it won’t/can’t default generate the move constructor.  Same for move assignment. That goes back to all inherited classes as well.

So maybe with work I could have rearranged class definitions so that most could have a default move constructor and move assignment generated, but I was in a super hurry and didn’t bother with figuring it out. I just implemented them and moved on.

Rusty

**Comment by Selmar** [comment]
> I have less knowledge on C++11 move semantics. What is the preferred way(or best practice) of move semantics(and `operator==`) for TinyGLTF code?

There isn't necessarily anything wrong, but it can be time-consuming to debug problems that arise from a missing field in a move operator.

I'll take a look at the problem with generation of the defaults tomorrow and see if I can find some ways around it.

**Comment by jrkoonce** [comment]
I can take a look tomorrow or Wednesday too if you don’t make progress. If you can use the default compiler generated version it has the benefit of not compiling if someone modifies the code in a way that breaks it. Where the explicit ones have to be maintained manually. 

Honestly I should do a complete pass over the tinygltf codebase and make sure it all using move semantics everywhere it can. The first rushed pass I’m sure missed a few places. I can spend a little more time on it for you. Maybe later tonight. 

Best practice is same for anyone using move semantics. Be careful of of using std::move on a variable declared const. That compiles and “works” but it is copying and not moving, but there is no warning or error.  It is a silent copy that looks like a move in code. Another big one if you are using std::vector, is the move constructor must be declared noexcept or std::vector can’t and won’t use it. So that is very important to you. Other best practices involve when you combine rvalue references with type deduction (like templates). That is for perfect forwarding. I don’t recall if you have any of that in tinygltf. 

Rusty

**Comment by syoyo** [comment]
PR #212 has been merged. So this issue should be ready close.
