### ISSUE TITLE
Undefined reference to tinygltf::FileExists

### ISSUE THREAD

**Issue by PuscasuRobert** [syoyo/tinygltf#203]
When i include the tiny_gltf.h file and i call the function LoadASCIIFromFile the compilers tells me a lot of functions from the file dont have an implementation. I opened the file to look for the implementations myself, they are there, its just that they are colored with "grey" and are inside a "#if defined" macro inside a "#if defined" macro. So the compiler doesnt see around 4000 lines of code, including those functions.

These are the lines:

https://ibb.co/f0LN5mL
https://ibb.co/HYpC8cf

Why is this happening? Im using codeblocks, c++11, GNU g++ compiler and im on a windows 64 machine.

**Comment by syoyo** [comment]
You need to define `TINYGLTF_IMPLEMENTATION`

https://github.com/syoyo/tinygltf#loading-gltf-20-model

**Comment by PuscasuRobert** [comment]
I already did that, and it doesnt work. Also, i had to rewrite the code. I had the error "The function fopen_s was not declared in this scope" and i replaced fopen_s with fopen. The more i try to modify the code the worse it gets.

**Comment by PuscasuRobert** [comment]
Also i had the eror "type errno_t was not declared in this scope". I had add "typedef int errno_t;"

**Comment by syoyo** [comment]
> "The function fopen_s was not declared in this scope"

The error does not happen in MSVC build(e.g. https://github.com/syoyo/tinygltf/blob/master/vcsetup.bat), so it may be specific to Windows + MinGW build(this combination is not well maintained). 

You can send us PR to fix build with Windows + MinGW configuration.

**Comment by PuscasuRobert** [comment]
https://github.com/PuscasuRobert/tinygltf-on-windows-with-mingw-compiler

Thank you, ive been stuck for the last week trying to make a GLTF parser to work, and to be fast as well.
The project uses SFML 2.5, GLM, OpenGL, but ive simplified the project as much as possible. Its a Codeblocks project.

**Comment by syoyo** [comment]
FYI I have confirmed mingw-gcc build of `loader_example.cc` works fine. So it will be a problem of codeblocks project configuration.
