### ISSUE TITLE
Allow parsing tolerancy

### ISSUE THREAD

**Issue by Bichette09** [syoyo/tinygltf#205]
When loading gltf binary file, if model format is omitted the library returns an error.
Here is a fix
[tiny_gltf.h_format.patch.txt](https://github.com/syoyo/tinygltf/files/3610734/tiny_gltf.h_format.patch.txt)

**Comment by syoyo** [comment]
According to the spec, 

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#chunks

> Client implementations must ignore chunks with unknown types to enable glTF extensions to reference additional chunks with new types following the first two chunks.

It looks we can ignore chunk type for 3rd, 4th, ... but the fist chunk and the second chunk must have valid type,  and the type of first chunk must be `0x4E4F534A` (JSON)

Do you have a glb file with chunk type other than `0x4E4F534A` for the first chunk?

**Comment by Bichette09** [comment]
Sorry for the disturbing, after verification it appears that is was gltf v1 files.
I close this ticket.
