### ISSUE TITLE
Material streaming

### ISSUE THREAD

**Issue by Bichette09** [syoyo/tinygltf#206]
The material serialization could lead to a null pbrMetallicRoughness field which is forbidden by the specification.
Here is a fix
[tiny_gltf.h_material.patch.txt](https://github.com/syoyo/tinygltf/files/3610742/tiny_gltf.h_material.patch.txt)

**Comment by syoyo** [comment]
This issue is discussed in https://github.com/syoyo/tinygltf/issues/204 and has been solved. I think this also solves your issue.

**Comment by Bichette09** [comment]
Ok, i see that this fix is quite recent. I will update my clone to check if it solve my issue.

**Comment by Bichette09** [comment]
This solve our issue.
Thank you for your prompt answer.
