### ISSUE TITLE
LoadASCIIFromFile didn't support wchar/wstring filename

### ISSUE THREAD

**Issue by harokyang** [syoyo/tinygltf#214]
If load file in Windows system, and the filename contain WideChar character, tinygltf can't open it

**Comment by syoyo** [comment]
Unicode build may be possible to read Windows' native UTF8(16?) filename with `LoadASCIIFromFile`

Another options is use `LoadASCIIFromString`, or implement `LoadASCIIFromStream`

https://github.com/syoyo/tinygltf/pull/178

PR of implementing `LoadASCIIFromStream` is welcome.

**Comment by harokyang** [comment]
I created a PR to support UTF-8 filepath
#216

**Comment by syoyo** [comment]
Thank! PR has been merged so this issue should be ready to close.

**Comment by harokyang** [comment]
Sure
