### ISSUE TITLE
#include <Windows.h> should be #include <windows.h>

### ISSUE THREAD

**Issue by avaskoog** [syoyo/tinygltf#22]
Hey there! Really cool library! Been using it to great success in the last few days. C:

But I was just about to cross-compile a Windows build for someone using MinGW on a Linux box when I got an error about Windows.h not being found in tiny_gltf.h. Looking online, I saw people using lowercase windows.h rather than uppercase Windows.h, so I tried making the change, and the compilation was successful.

Probably the compiler on Windows is case-insensitive and so it works either way, but it has to be lowercase on MinGW on Linux at least. Too quick a fix for me to do the whole pull request routine for, since it's just a matter of one letter in one file, but it's on line 683. c;

Fixed it myself for myself, but might as well fix it for others in the future. Thanks!

**Comment by syoyo** [comment]
>  Been using it to great success in the last few days. C:

Thanks!

For some reason, I choose upper case `Windows.h`, but it looks `windows.h` should work on many compilers,

https://stackoverflow.com/questions/15466613/lowercase-windows-h-and-uppercase-windows-h-difference

So I have fixed it by using lower-case `windows.h`.

More better way is to detect compiler using more ifdef switches.
