### ISSUE TITLE
MinGW-w64 compilation error because of utf8 filename strings

### ISSUE THREAD

**Issue by Tirondzo** [syoyo/tinygltf#221]
Error started with this commit: https://github.com/syoyo/tinygltf/commit/5cecef2b92ad0cb4cee3271ab0910e47229f898d

Because of fstream(wchar_t *, ..) is not standard C++11/14
Discussions:  https://stackoverflow.com/a/822032
https://stackoverflow.com/a/5382504

Btw, this http://utf8everywhere.org/ is a good info, but doesn't help much
But this one seems to be working: https://gist.github.com/Youka/d5313cdab9108b73282a

So I tested this on windows with MinGW-w64 and yup, everything seems fine. Sadly I have no opportunity to test it with new VisualStudio (I have 14.0 only).

Anyway, I did Pull Request that fixes that problem, you can use, edit, test it, whatever...

**Comment by Tirondzo** [comment]
Also, may be it's better to use `_wsopen_s` instead of `_wopen`

**Comment by syoyo** [comment]
https://github.com/OpenImageIO/oiio/issues/1349

Found  another example to fix UTF-8 filepath on MinGW.

So we need to use

```
#ifdef _WIN32
#ifdef _MSC_VER
  ... VC stuff
#elif defined(__GLIBCXX__)
  .. mingw stuff
#else 
  #error "Unknown compiler"
#endif 

#else 
// Assume posix(linux and macOS)
#endif
```

**Comment by Tirondzo** [comment]
I don't think there are any reason to separate VC and MinGW.
There is already `_wfopen_s` in code, and `stdio_filebuf` is just a smart wrapper around file descriptor that allows to use stream operations and that closes file descriptor on destroy.

But may be I'm wrong, I didn't test it on VC.

**Comment by syoyo** [comment]
`stdio_filebuf` is a MinGW extension. VC build is failing due to it > https://ci.appveyor.com/project/syoyo/tinygltf/builds/28732803

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/commit/a471770f38d7a821e869301168128834e6c906b5

MinGW fix has been done in this commit.

At least I have confirmed build works well with MinGW cross compiler.

**Comment by Tirondzo** [comment]
Looks good but a lot of code duplication
I think it would be better to write like this:
`#if defined(_WIN32) && defined(__GLIBCXX__)`
MinGW
`#else`
old code here
`#endif`

`#elif defined(_WIN32) && defined(_MSC_VER)`
VC. Code here is the same as in `#else` branch so it can be merged

**Comment by Tirondzo** [comment]
But that's about code style.
Issue is resolved and I think it can be closed.

Thank you!
