### ISSUE TITLE
padding_size incorrect?

### ISSUE THREAD

**Issue by epajarre** [syoyo/tinygltf#224]
Just starting to play with tinygltf, but it looks like that the padding_size calculation in WriteBinaryGltfStream might be incorrect:

`const int padding_size = content.size() % 4;`

something like

`const int padding_size = (4 - content.size() % 4) % 4;`

should give the value which is needed in order to pad the content to multiple of 4.

Eero

**Comment by syoyo** [comment]
Oh, good catch!

https://stackoverflow.com/questions/3407012/c-rounding-up-to-the-nearest-multiple-of-a-number/9194117

```
int roundUp(int numToRound, int multiple)
{
    if (multiple == 0)
        return numToRound;

    int remainder = numToRound % multiple;
    if (remainder == 0)
        return numToRound;

    return numToRound + multiple - remainder;
}
```

or we can use this calculation for better readability.

**Comment by syoyo** [comment]
I think I've fixed it. Adding a regression test would be nice though.
