### ISSUE TITLE
preprocessor and  'not'

### ISSUE THREAD

**Issue by epajarre** [syoyo/tinygltf#225]
Hi,
Line 5248:
```C++
#if (defined(__cpp_exceptions) || defined(__EXCEPTIONS) || \\
     defined(_CPPUNWIND)) &&                               \
    not defined(TINYGLTF_NOEXCEPTION)
```
Microsoft compiler does not seem to like the operator 'not'. As it is preprocessor code it also seems that the compilation happens, but I don't trust if behaves as intended.

replacing not with ! makes compiler happy (or at least creates no warnings)

 Eero

**Comment by syoyo** [comment]
Oh, good catch.

Fixed!

FYI, `not` is an alternative keyword > https://en.cppreference.com/w/cpp/language/operator_alternative
