### ISSUE TITLE
Uri with percent encoding

### ISSUE THREAD

**Issue by digimatic** [syoyo/tinygltf#228]
It seems that Images with percent encoded path is not decoded. 
For example:
"images": [ { "uri": "Lunchroom%5Ctexturer%2FLight_button.jpg"} ]

As far as I can see, that is valid glTF as it is a json-schema uriref that refers to the RFC3986: https://tools.ietf.org/html/rfc3986#section-2.4

**Comment by syoyo** [comment]
I see. Currently TinyGLTF does nothing for `uri` string.

> As far as I can see, that is valid glTF as it is a json-schema uriref that refers to the RFC3986

There is a github issue at glTF repo:
 
https://github.com/KhronosGroup/glTF/issues/838

So, at least we need to parse percent encoding characters
 
https://tools.ietf.org/html/rfc3986#section-2.1

**Comment by digimatic** [comment]
I searched for some decoder to use. Maybe this one: https://uriparser.github.io/

**Comment by syoyo** [comment]
I have glimpsed uriparser and found its too big to embed it to tinygltf.

Instead, I have grabbed dlib's uriencode http://dlib.net/dlib/server/server_http.cpp.html (from this SO https://stackoverflow.com/questions/18307429/encode-decode-url-in-c ) to tinygltf and made `uri-decode` branch https://github.com/syoyo/tinygltf/tree/uri-decode .

@digimatic Please test  `uri-decode` branch. 

At least percent-encoded character in URI should now be correctly handled when reading external files.
(URI string in `Image`, `Buffer` are still stored with original values(i.e. percent-encoded characters are not decoded))

**Comment by digimatic** [comment]
Ok thanks, I will try it out.

**Comment by digimatic** [comment]
We have merged this in our code base and so far it seems to work fine.

**Comment by syoyo** [comment]
Thanks! Merged `uri-decode` into `master`. So now this issue should be ready to close.
