### ISSUE TITLE
Crash when writing an empty buffer

### ISSUE THREAD

**Issue by nfrechette** [syoyo/tinygltf#229]
If a Buffer has a size of 0 and we are embedding it into a glTF file, the following code crashes:

```
static void SerializeGltfBufferData(const std::vector<unsigned char> &data,
                                    json &o) {
  std::string header = "data:application/octet-stream;base64,";
  std::string encodedData =
      base64_encode(&data[0], static_cast<unsigned int>(data.size()));
  SerializeStringProperty("uri", header + encodedData, o);
}
```

When data has a length of 0, `&data[0]` crashes with MSVC in debug due to the invalid access. Use data.data() instead which will return a pointer to an empty string.

The function right below does something similar and likely might crash.

```
static bool SerializeGltfBufferData(const std::vector<unsigned char> &data,
                                    const std::string &binFilename) {
  std::ofstream output(binFilename.c_str(), std::ofstream::binary);
  if (!output.is_open()) return false;
  output.write(reinterpret_cast<const char *>(&data[0]),
               std::streamsize(data.size()));
  output.close();
  return true;
}
```

Buffers with 0 length can arise when glTF files are part of a pipeline. For example, if I compress glTF animations, I have to create a new buffer with the data. The old buffer cannot be removed because other things might reference buffers and removing it would change the indices (e.g. some custom extension, somewhere). All that can be done is to reset it to an empty length.

This issue affects release v2.2.0 and the current master branch.

**Comment by syoyo** [comment]
I see.

@nfrechette do you have a minimal glTF file for `uri` with a buffer of size 0?
I'd like to know how to encode empty buffer into `uri`(base64).

The latter case can trivially be fixed by checking the input `data` size.

**Comment by nfrechette** [comment]
Base64 encoding an empty string yields an empty string so I believe it should look like this: `data:application/octet-stream;base64,`

**Comment by syoyo** [comment]
@nfrechette  Added size check in this commit: https://github.com/syoyo/tinygltf/commit/a11f6e19399f6af67d7c57909e8ce99d20beb369

At least serialization with buffer size 0 should work well.
