### ISSUE TITLE
Extensions of primitive serialized as the extensions of mesh

### ISSUE THREAD

**Issue by itainter** [syoyo/tinygltf#231]
Hi @syoyo , thanks a lot for this useful library and I'm using it in our works now.
Today when I serialized something and found a issue that the extensions map in primitive was wrongly  write into the extensions of mesh.
I have create a PR https://github.com/syoyo/tinygltf/pull/230 for this fix.

**Comment by syoyo** [comment]
Thanks! Merged! > PR #230
