### ISSUE TITLE
tiny_gltf.h line 815, BufferView ctor doesn't use members order correctly

### ISSUE THREAD

**Issue by ziocleto** [syoyo/tinygltf#234]
When building on Apple clang version 11.0.0 (clang-1100.0.33.12)+ and probably others, this constructor has a wrong members initialization order:

`  BufferView() : buffer(-1), target(0), byteOffset(0), byteLength(0), byteStride(0),  dracoDecoded(false) {}`
 
It should be: 

`  BufferView() : buffer(-1), byteOffset(0), byteLength(0), byteStride(0), target(0), dracoDecoded(false) {}`
 
_(target(0)is moved second to last)_ to avoid compiler warnings and possibly other side effects.

I have an extremely simple PR fix ready if interested.

Cheers,
Dado.

**Comment by syoyo** [comment]
Thanks! I have suppressed some clang warnings by increasing clang compiler warnings.
(`-Wall -Werror -Weverything -Wno-c++11-long-long -Wno-c++98-compat`)
