### ISSUE TITLE
Missing iOS header

### ISSUE THREAD

**Issue by avaskoog** [syoyo/tinygltf#24]
Hello again! I have another quick fix to suggest after another cross-compiling adventure. c:

I got errors compiling to iOS because the checks for `TARGET_OS_IPHONE` failed and the library ended up trying to do things it was not meant to try to do on iOS; this is because you forgot to do this in order to include the definition (which in my experience is not meant to be set by the IDE for an iOS project but by including this file):

```
#if __APPLE__
    #include "TargetConditionals.h"
#endif
```

I added it right before `namespace gltf` but feel free to put it where you think makes sense and that should fix it. c:

**Comment by syoyo** [comment]
Good catch!

I think I have fixed it now!

**Comment by avaskoog** [comment]
Cool! Can confirm that with the two fixes I've suggested at least the following works:

* macOS using LLVM 
* iOS using LLVM
* Linux using GCC
* Windows using MinGW
* Android using CrystaX (NDK drop-in replacement) GCC
* Web using Emscripten (LLVM)

**Comment by syoyo** [comment]
Super cool! Thank you!

**Comment by syoyo** [comment]
And listed up it in README: https://github.com/syoyo/tinygltf#features
