### ISSUE TITLE
Accessor componentType support double(5130)?

### ISSUE THREAD

**Issue by jsqabcjsq** [syoyo/tinygltf#248]
In tiny_gltf.h, define TINYGLTF_COMPONENT_TYPE_DOUBLE (5130), but I find that GLTF 2.0 is not support this type.

![image](https://user-images.githubusercontent.com/27665833/75854419-1ceb2a80-5e2b-11ea-80a4-8cbe3eb239b3.png)
reference:
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#floating-point-data

**Comment by syoyo** [comment]
Double itself is not defined in glTF 2.0, but it would be handy to have it in some situation(e.g. use glTF for CAD data)

**Comment by jsqabcjsq** [comment]
> Double itself is not defined in glTF 2.0, but it would be handy to have it in some situation(e.g. use glTF for CAD data)

So we cannot store mesh data in double type?

**Comment by syoyo** [comment]
You can store mesh data as double.  Not sure other glTF viewer/tools supports loading/saving double-typed value though.

**Comment by jsqabcjsq** [comment]
> You can store mesh data as double. Not sure other glTF viewer/tools supports loading/saving double-typed value though.

I understand. Thanks for your reply.
