### ISSUE TITLE
SerializeGltfBufferData fails when compiling with msys2+mingw on Windows

### ISSUE THREAD

**Issue by LHLaurini** [syoyo/tinygltf#253]
In `SerializeGltfBufferData`, `_wopen` always returns -1 for me.

If I replace
```C++
#if defined(__GLIBCXX__)  // mingw
  int file_descriptor =
      _wopen(UTF8ToWchar(binFilename).c_str(), _O_WRONLY | _O_BINARY);
  __gnu_cxx::stdio_filebuf<char> wfile_buf(file_descriptor, std::ios_base::in);
  std::ostream output(&wfile_buf);
  if (!wfile_buf.is_open()) return false;
#elif defined(_MSC_VER)
  std::ofstream output(UTF8ToWchar(binFilename).c_str(), std::ofstream::binary);
  if (!output.is_open()) return false;
#else
```
with just
```C++
#if defined(__GLIBCXX__) || defined(_MSC_VER)
  std::ofstream output(UTF8ToWchar(binFilename).c_str(), std::ofstream::binary);
  if (!output.is_open()) return false;
#else
```
it works just fine (even with UTF-8 filenames). It requires C++17, however.

**Comment by LHLaurini** [comment]
It seems `_wopen` fails if the file doesn't already exist, because of the `_O_WRONLY` flag. If I replace it with `_O_CREAT` it works (and doesn't require C++17). Like this:
```C++
int file_descriptor =
      _wopen(UTF8ToWchar(binFilename).c_str(), _O_CREAT | _O_BINARY);
```

**Comment by syoyo** [comment]
@LHLaurini Thanks for the report!

Which Windows version and msys2+mingw version do you use? I think the situation depends on Windows version(we assume all people use Windows 10) and mingw version.

**Comment by LHLaurini** [comment]
I'm using Windows 10 (fully updated) and since msys2 is a rolling release software distro, I'm using the latest MinGW-w64 binaries available (forgot to mention I was using MinGW-w64).

**Comment by syoyo** [comment]
@LHLaurini Thanks for the version infos. The PR has been merged!
