### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by koiava** [syoyo/tinygltf#26]
https://github.com/syoyo/tinygltf/blob/660256062b5748fc56ef53303df7f58d642cd5d5/examples/raytrace/gltf-loader.cc#L48

Seams like it should return true here.

I tried running after that and it crashed :( (on windows)
I've got some warning at beginning also which I just disabled :|

**Comment by syoyo** [comment]
Thank your for finding an issue! Fixed!

**Comment by koiava** [comment]
That was fast :D
