### ISSUE TITLE
light.range > 0

### ISSUE THREAD

**Issue by mklefrancois** [syoyo/tinygltf#260]
In the function `SerializeGltfLight()`, the serialization of the light range should be done only if the range is bigger than 0.

Something like this could fix it:
~~~~
  if(light.range > 0)
  {
    SerializeNumberProperty("range", light.range, o);
  }
~~~~

Reference: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual

Many thanks for fixing so quickly all the previous issues.

**Comment by syoyo** [comment]
Thanks! Now fixed!
