### ISSUE TITLE
Really slow compilation

### ISSUE THREAD

**Issue by nickenchev** [syoyo/tinygltf#262]
Hey, for some reason when I include the following code in my cpp file:
```
#define tinygltf_implementation
#define tinygltf_use_cpp14
#define tinygltf_no_external_image
#define tinygltf_no_stb_image
#define tinygltf_no_stb_image_write
#include "tiny_gltf.h"
```

My compilation becomes literally 4/5 times slower, at least. I've got this block at the top of a single cpp file in my project, so I'm not sure what I could be doing wrong.

Thanks

**Comment by syoyo** [comment]
If you enable optimization and/or address-sanitizer, compilation will get slow.

You may use clang to profile the bottleneck https://pharr.org/matt/blog/2019/10/23/profiling-the-pbrt-build.html

**Comment by nickenchev** [comment]
Hey thanks for the reply. I don't have anything special enabled, I just notice it becomes VERY slow when I add tinygltf stuff into my cpp files.

This is the only thing I have set for my compilation flags:
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_BUILD_TYPE Debug)
```
I can take a look at profiling the build and come back with more details.

**Comment by nickenchev** [comment]
Just ran my compilation with "-ftime-report", so here are the logs:

This is with the tinygltf code included:
https://pastebin.com/giDfbzZJ

and this is without:
https://pastebin.com/N4sbKwNt

Of particular note is the "code generation time"

```
===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 9.7807 seconds (9.8258 wall clock)
 
   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
   8.2289 (100.0%)   1.5518 (100.0%)   9.7807 (100.0%)   9.8258 (100.0%)  Clang front-end timer
   8.2289 (100.0%)   1.5518 (100.0%)   9.7807 (100.0%)   9.8258 (100.0%)  Total
```

VS

```
===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 2.0340 seconds (2.0393 wall clock)
 
   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
   1.9112 (100.0%)   0.1228 (100.0%)   2.0340 (100.0%)   2.0393 (100.0%)  Clang front-end timer
   1.9112 (100.0%)   0.1228 (100.0%)   2.0340 (100.0%)   2.0393 (100.0%)  Total
```

**Comment by syoyo** [comment]
8 seconds to compile with TINYGLTF_IMPLEMENTATION is a reasonable number.

**Comment by nickenchev** [comment]
So you believe its acceptable that a single library would add 8 seconds to every single recompilation of this compile unit? Considering most cpp files take <1 second to recompile?

**Comment by syoyo** [comment]
https://devblogs.microsoft.com/cppblog/profiling-template-metaprograms-with-cpp-build-insights/

@nickenchev Can you please try C++ build insights? It would give detailed analysis of C++ compilation bottleneck.

**Comment by nickenchev** [comment]
To be honest, I've built my own GLTF2 parser now which I'll be using for my own engine. I'll find some time and try to help narrow down the bottleneck here.
