### ISSUE TITLE
Incorrect/Undefined Loading Of ASCII GLTF In RapidJson When Array Redefined. 

### ISSUE THREAD

**Issue by CealedLion** [syoyo/tinygltf#264]
In GLTF exporters such as Sketchfab, they export with multiple ""bufferViews":" or of such.

 When this happens the loader overwrites the previous ""bufferViews":" array.

This happens with all arrays in the ASCII file. A fix or some support for this would be nice.

**Comment by syoyo** [comment]
Please post a minimal reproducible glTF file

**Comment by CealedLion** [comment]
[example.txt](https://github.com/syoyo/tinygltf/files/4707036/example.txt)

`    "bufferViews" : [
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 0
        },
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 288
        }
    ],
	"bufferViews" : [
        {
            "buffer" : 0,
            "byteLength" : 192,
            "byteOffset" : 576
        },
        {
            "buffer" : 0,
            "byteLength" : 72,
            "byteOffset" : 768
        }
    ],`
this section is the problem area in that file, as opposed to writing it like 

`    "bufferViews" : [
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 0
        },
        {
            "buffer" : 0,
            "byteLength" : 288,
            "byteOffset" : 288
        },
        {
            "buffer" : 0,
            "byteLength" : 192,
            "byteOffset" : 576
        },
        {
            "buffer" : 0,
            "byteLength" : 72,
            "byteOffset" : 768
        }
    ],`

**Comment by syoyo** [comment]
https://github.com/KhronosGroup/glTF/issues/846

Duplicated fields(keys) are undefined in JSON, and glTF 2.0 does not allow it

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding

Please post an issue to Sketchfab
