### ISSUE TITLE
Ubuntu 20.04 broken support

### ISSUE THREAD

**Issue by helixd-2k18** [syoyo/tinygltf#268]
When I running any tinygltf example, I always getting `segmentation fault` in basic_script library... Also used C++20 standard. 

```cpp
    tinygltf::Model model = {};
    tinygltf::TinyGLTF loader = {};
    std::string err = "", wrn = "";
    const bool ret = loader.LoadASCIIFromFile(&model, &err, &wrn, "Cube.gltf");
```

**Comment by syoyo** [comment]
You should not use C++20. There is no stable C++ compiler which supports C++20.

Please use address sanitizer or C++ debugger to find where `segmentation fault` happens.
