### ISSUE TITLE
Empty array when not using RapidJson

### ISSUE THREAD

**Issue by gmendieta** [syoyo/tinygltf#270]
When not using Rapid Json and create an Array value, which then it's empty, the result is a NULL attribute. I would expect to be an empty array. 

It could be fixed adding "obj = json::array({});" in line 6393, explicitly initializing obj as an array before adding elements.
Sorry to not make a Pull request. I will next time ;)

**Comment by syoyo** [comment]
There is no corresponding code in line 6393 in `master` branch.

https://github.com/syoyo/tinygltf/blob/5622d2762dc43fb3d3913389c0706dc7a9b02282/tiny_gltf.h#L6393

PR is much appreciated.

**Comment by gmendieta** [comment]
You are right. I meant i would add a line with that explicit initialization, so array json object is created instead of null one.

**Comment by syoyo** [comment]
BTW, empty array is not allowed in glTF 2.0 spec.

https://github.com/KhronosGroup/glTF/issues/916

It may be better to raise an error instead of making empty array JSON for empty array data.
