### ISSUE TITLE
No data in Light vector ->  std::vector<Light> lights

### ISSUE THREAD

**Issue by AMSDesha** [syoyo/tinygltf#271]
I exported a gltf model from 3DS max which contain Free Direct lights.
Once I load the gltf model from tinygltf ,
"std::vector<Light> lights" does not contain any data while "std::vector<Node> nodes" contain lights as nodes.
 Why no data in light vector ?  Please advice.

**Comment by syoyo** [comment]
You should attach .gltf

**Comment by AMSDesha** [comment]
Sorry what do you mean by "attach .gltf" ?
I simply load the file as below 
`loader.LoadASCIIFromFile(&model, &err, &warn, input_filename );`

Is there any thing else need to be done ?

**Comment by syoyo** [comment]
> Sorry what do you mean by "attach .gltf" ?

3ds max exported file.

**Comment by syoyo** [comment]
Use a template to file an issue: https://github.com/syoyo/tinygltf/issues/new/choose
