### ISSUE TITLE
No data in Light vector -> std::vector<Light> lights

### ISSUE THREAD

**Issue by AMSDesha** [syoyo/tinygltf#272]
**Describe the issue**

Followed by #271 

I exported a gltf model from 3DS max which contain Free Direct lights.
I loaded the gltf model from tinygltf like below.

`input_filename = gltf_file_name`
`loader.LoadASCIIFromFile(&model, &err, &warn, input_filename );`

**"std::vector lights" does not contain any data** while "std::vector nodes" contain lights as nodes.
Why no data in light vector ? Please advice.

**To Reproduce**

- Windows10
- MSVC version 15.9, No specific compiler options.
- [gltfdata.zip](https://github.com/syoyo/tinygltf/files/4843805/gltfdata.zip)

**Expected behaviour**

I expect data in "std::vector lights" of the Model class, Once loaded the .gltf file

**Screenshots**
-

**Additional context**

**Comment by syoyo** [comment]
There is no KHR_lights_punctual description in glTF.

You should export light data to follow KHR_lights_punctual specification.

https://github.com/KhronosGroup/glTF/pull/1223

**Comment by AMSDesha** [comment]
It worked.
Thank you
