### ISSUE TITLE
Clean up examples

### ISSUE THREAD

**Issue by daemyung** [syoyo/tinygltf#275]
**Describe the issue**

tinygltf is very good open source project and it is loved from many people. Only one weak point on this project is that examples are not good enough.

**Expected behaviour**

If you are ok then I will work for refactoring examples. Please let me know your idea.

**Comment by syoyo** [comment]
There is already (nearly) full featured glTF examples using TinyGLTF.
 
https://github.com/SaschaWillems/Vulkan-glTF-PBR
(Both supporting skinning and morph is todo: https://github.com/SaschaWillems/Vulkan-glTF-PBR/issues/6 )

so at least we won't need a full-featured example.

Example codes in TinyGLTF are not maintained well, so clean-up and refactoring are appreciated! I think merging `basic` and `glview` example and polishing it(still stick to use OpenGL for cross-platform support) would be a good direction.

**Comment by daemyung** [comment]
Ok I will drive :) but it will be slow because I can do it on my free time.
