### ISSUE TITLE
Can i output more vertex information?

### ISSUE THREAD

**Issue by SuRuiMeng** [syoyo/tinygltf#276]
When I change the number of vertices and indexes, but the data is stored sequentially.how do I export the model?

**Comment by syoyo** [comment]
Please use issue template and precisely describe your issue/question.

**Comment by enjoybo** [comment]
> When I change the number of vertices and indexes, but the data is stored sequentially.how do I export the model?

@SuRuiMeng Hi, have you solved the problem now?
