### ISSUE TITLE
Could you make the version tag for the latest?

### ISSUE THREAD

**Issue by daemyung** [syoyo/tinygltf#282]
**Describe the issue**

tinygltf also can be downloaded by vcpkg but it's not latest. I have raised up the issue on vcpkg but their answer is v2.4.x is not leased yet. But I can see v2.4.2 is released on your source code. I think vcpkg manges the version using the git tag and there is no more version tag after v2.2.0. So could you make v2.4.2 tag?

**Comment by syoyo** [comment]
Please ask vcpkg people for the support.

TinyGLTF itself does not provide vcpkg.

As you know, tinygltf is a header-only library so we don't recommend to use vcpkg(precompiled binary)

**Comment by syoyo** [comment]
For tagging, I have tagged current `master` as `v2.4.0`

**Comment by daemyung** [comment]
Thanks I have shared your opinion and microsoft accept to sync up the latest tinygltf on vcpkg.
