### ISSUE TITLE
load material data

### ISSUE THREAD

**Issue by HappyKuTou** [syoyo/tinygltf#285]
**Describe the issue**

I have to convert obj to gltf
data in obj mtl file is not pbr data
how can I fill the tinygltf material struct after load obj mtl file

**To Reproduce**

- OS win10
- Compiler vs2019 

**Expected behaviour**

I need to write mtl data in tinygltf material struct

**Screenshots**
this is tinygltf material struct 
![image](https://user-images.githubusercontent.com/42768162/91420304-17751700-e887-11ea-95ef-a81b9b200997.png)

this is obj mtl file
![image](https://user-images.githubusercontent.com/42768162/91420380-35427c00-e887-11ea-8387-84871447f1d5.png)

**Comment by syoyo** [comment]
The issue is note related to TinyGLTF.

You need to find a solution from glTF community: https://www.khronos.org/gltf/

Contributing .obj mtl conversion code to glTF PBR is always welcome, though(please send a PR)

**Comment by HappyKuTou** [comment]
thanks for your reply, so gltf is not support Phong Shading data currently,
it can't load data in .obj mtl, right?

Syoyo Fujita <notifications@github.com> 于2020年8月27日周四 下午6:20写道：
