### ISSUE TITLE
What's the intension of "wrapR" in sampler?

### ISSUE THREAD

**Issue by zhuda** [syoyo/tinygltf#287]
**Describe the issue**

Hi, What's the intension of introducing "wrapR" in sampler? From the spec only "wrapS" and "wrapT" is supported.
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplers

We are using official glTF validation tool and it report this property as unexpected. 

**To Reproduce**

n/a

**Expected behaviour**

n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/3140101/91627786-933ca400-e9ec-11ea-8f85-be840a83fd55.png)

**Additional context**
n/a

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/blob/91da29972987bb4d715a09d94ecd2cefd3a487d4/tiny_gltf.h#L614

As described in the code, its TinyGLTF extension.

If you do not want to it, you can send a PR which moves "wrapR"  to glTF extensions or extras.

**Comment by nithinp7** [comment]
We are also running into this issue of unexpected inclusion of wrapR. Moving wrapR to glTF extensions or extras might also be problematic in our case if there is no way to disable the writing of the extensions or extras.

**Comment by syoyo** [comment]
@nithinp7 I see. As far as I know no one uses  `wrapR` parameter so deleted it(I added it for possible volumetric texture support in glTF(-next)).
