### ISSUE TITLE
Color per vertex problem in glview/tinygltf

### ISSUE THREAD

**Issue by mufti11** [syoyo/tinygltf#288]
i am currently testing tinygltf as gltf import libary, especially the
glview code example.
when i use object mode ->  vertex paint mode in blender 2.8, the object
is shown with colorpervertes true, but the exported gltf file is shown
in glview
with colorPerVertex false 8-(

Is this a problem of blender or a problem of tinygltf ?

What show other gltf viewers for the "untitled.glb" in the attachments ?

https://gltf-viewer.donmccurdy.com/
show something similar to blender 2.8, but unlike glview 8-(
view3dscnene shows it smilr to blende...

**Screenshots**

http://wdune.ourproject.org/examples/insideblender2.8.png
http://wdune.ourproject.org/examples/glview.png
http://wdune.ourproject.org/examples/untitled.glb

**Comment by syoyo** [comment]
You should use issue template to file an issue: https://github.com/syoyo/tinygltf/issues/new?assignees=&labels=&template=issue-report.md&title=

**Comment by capnm** [comment]
Just some hints.

There is an option for export vertex colors in blender:
https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#geometry
![grafik](https://user-images.githubusercontent.com/4047289/89136426-f9d8ba00-d533-11ea-9337-5ab7c5c37166.png)

The GLTF specification states that vertex colors must be mixed with materials. If it doesn't happen, something is broken ...
