### ISSUE TITLE
Questions about basic example

### ISSUE THREAD

**Issue by NukeBird** [syoyo/tinygltf#289]
Why only one vao used? As far as I understand how it works, it remembers GL_ARRAY_BUFFER/GL_ELEMENT_ARRAY_BUFFER and attribute settings (glVertexAttribPointer/glEnableVertexAttribArray). Do I understand this correctly: assumption was made that GL_ARRAY_BUFFER is only one and GL_ELEMENT_ARRAY_BUFFER changes dynamically? If so, can you recommend any other way to work with vao?

Can you explain more when to use glDrawArrays instead of glDrawElements? When no GL_ELEMENT_ARRAY_BUFFER provided primitive.indices will be -1?

Sorry if my questions a bit silly, I really trying my best to get everything right

**Comment by syoyo** [comment]
You should use issue template: https://github.com/syoyo/tinygltf/issues/new?assignees=&labels=&template=issue-report.md&title=
