### ISSUE TITLE
What to do with bufferView.byteStride when it is unspecified.

### ISSUE THREAD

**Issue by Ybalrid** [syoyo/tinygltf#29]
Hi,

I bumped into a small problem while implementing the loading of glTF assets into a project via this library.

When the byteStride of a buffer view is not defined inside the glTF file, the glTF standard states that this means "the data is tightly packed".

The current way tinygltf handle this is by putting the byteStride member of the bufferView object to zero.

I think a saner thing to do as a loading library, would be to actually put there the value it should have when reading the buffer as just a plain array of the underlying datatype.

This permit the library user to just iterate through the data with the same code, with no regards into checking if the byteStride is 0, and thus making this kind of code work all the time.

In that case, making byteStride be `sizeof(component_type) * countOfElementsInType` Where `countOfElementsInType` is equal to the number of variable you need to get one element in the array (e.g. for a buffer of FLOAT that represent a VEC3, be equal to `sizeof(float) * 3`)

```C++
for(size_t i = 0; i < bufferLenghtInElements; ++i)
{
    //Access the data of each element of the buffer
    buffer.data[(bufferView.byteOffset + accessor.byteOffset) + i * bufferView.byteStride]
}
```

Strictly speaking, this is okay according to the representation of the file we do here in C++ in regards to the data that was in the JSON file, and how the specification say we should interpret it.

Here's where the standard defines what not setting the byteStride means : https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#data-alignment 

What do you think about this ?

Thanks again for the awesome work on this "tiny" library ;-)

**Comment by syoyo** [comment]
> The current way tinygltf handle this is by putting the byteStride member of the bufferView object to zero.

As commented here

https://github.com/syoyo/tinygltf/blob/devel/tiny_gltf.h#L1633

we cannot determine actual byteStride until any `Accessor` references  the `bufferView`, and `0` is allowed in OpenGL API(e.g. https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml )

Although this would be problematic when interacting `glTF` data structure directly without calling OpenGL(e.g. writing your own renderer, data converters).

Also, the glTF spec says,

> byteStride must be defined, when two or more accessors use the same bufferView.

So I think at least we can implement a functionality to check if `byteStride` must be defined or not depending on how many accessors are referencing the same bufferView data during  glTF data parsing.

Then, we may need to provide an utility function to compute `byteStride` when interacting with Accessor and bufferView in the runtime stage(i.e., **after** parsing glTF data).

**Comment by Ybalrid** [comment]
Well, I'm working on a glTF importer for the OGRE rendering engine (C++ library for doing 3D graphics, that does support PBR materials out of the box in it's version 2.1 that is still in development. But it's using it's own binary format and there's no tools to properly export model and materials to it yet.)

(off topic; the main reason I'm interested in this is because Ogre is using it's own file format, but there's no "good" workflow to produce those files. I'm expecting that glTF, being a standard from the Khronos group, will get a lot of great tools for artists and developers to create and process theses files. This time, it's a file format that has everything you want without ambiguity, and where the raw data is stored in binary and all theses great stuff)

OGRE is an API agnostic library. it manages (and optimizes) how the data is put on the GPU itself depending on the "RenderSystem" plugin that is used. Could be OpenGL, Direct 3D, or even Metal on Apple devices.

What I was doing was to extract the buffer content from the glTF file, rearranging them in a format expected by Ogre (basically just making a big interleaved vertex buffer for each mesh primitives that are put into ogre as multiple "subMesh" of a mesh)

It was just a an idea, since I was pulling my hairs trying to understand how my code wasn't doing what it was supposed to do when I saw that it was multiplying all the indexing by zero. But that's just me being me ;-) 

> Then, we may need to provide an utility function to compute byteStride when interacting with Accessor and bufferView in the runtime stage(i.e., after parsing glTF data).

Maybe a simple method added into the `Accessor` class could provide that info? It's not really important, 

> Then, we may need to provide an utility function to compute byteStride when interacting with Accessor and bufferView in the runtime stage(i.e., after parsing glTF data).

I agree on that. This is not a thing that sould be dealt with during the actual parsing of the glTF file. It's just an higher-level API consideration. 

To be frank, the targeted users of this library are other developers that are working on integrating this file format with their tool, so this is the kind of stuff they should be able to figure out by just looking a a documentation.

This particular point should be highlighted a bit more clearly when a documentation/tutorial for the usage of this library will be written.

I (and I'm in no way a professional, I'm just a bored student 😉 )  was able to get my way around most of the data exposed by the `tinygltf::Model` by looking up the non-normative poster that serve as an overview on the main page of the glTF github repository. It's *super easy* to understand.

There's a few oddities like this that could be improved, Right now I'm on the Material side of thing, and It took a bit of looking around to find where to find the index of the texture a material was referencing.
Right now I'm iterating through the different `std::map` inside the material object, and I a key like `"baseColorTexture"`, I'm pulling the value from the index field of the enclosed map. This could be made a little bit nicer for the user ^^"

**Comment by syoyo** [comment]
> Well, I'm working on a glTF importer for the OGRE rendering engine 

Super cool!

>> Then, we may need to provide an utility function to compute byteStride when interacting with Accessor >> and bufferView in the runtime stage(i.e., after parsing glTF data).
>> 
> Maybe a simple method added into the Accessor class could provide that info?

Adding API to `Accessor` would make sense. I'll consider to implement an API which compute byte strides.
 
> There's a few oddities like this that could be improved, Right now I'm on the Material side of thing,

PBR thing is still not yet perfect and requires improvements(lack of unit tests, example codes, better name lookup etc). So PR  is always welcome!

**Comment by Ybalrid** [comment]
> PBR thing is still not yet perfect and requires improvements(lack of unit tests, example codes, better name lookup etc). So PR is always welcome!

Right now I'm getting by with the current functionality, but If I can improve something, I'll certainly open some pull requests for you to look at ;-)

**Comment by syoyo** [comment]
I have added `Accessor::ByteStride` utility function to compute byteStride from Accessor/BufferView pair.

https://github.com/syoyo/tinygltf/commit/584f8c0ddfb29c7d9c750b5addc9784985a7de65

@Ybalrid , please try recent `devel` branch so that this fits your use case.

**Comment by Ybalrid** [comment]
Will get back to you after testing it 😉

**Comment by Ybalrid** [comment]
Seems to works as expected. 👍 

I guess I'm closing the issue now 😄

**Comment by syoyo** [comment]
Super cool!
