### ISSUE TITLE
Old version json.hpp

### ISSUE THREAD

**Issue by nikita1prasolov** [syoyo/tinygltf#293]
**Describe the issue**
You have use old version of nlohmann/json - 3.5.0, feature request - switch to latest version 3.9.1

**To Reproduce**
- OS - all supported
- Compiler, compiler version, compile options - all supported
- Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data - not applicable

**Expected behaviour**
Users can use improved and addition functionaliies

**Screenshots**
- not applicable

**Additional context**
Best regards, your user, Kit!

**Comment by syoyo** [comment]
You can use your own json.hpp with `TINYGLTF_NO_INCLUDE_JSON` ifdef: https://github.com/syoyo/tinygltf#compile-options

Currently there should be no issues using current json.hpp in TinyGLTF, so there isn't strong reason to update it.
We would only accept upgrading json.hpp if it gives faster C++ compilation time than the old version.

PR with benchmarks(C++ compile time) is welcome!

**Comment by meatN** [comment]
Thank you!
