### ISSUE TITLE
'null' material written when giving default baseFactors for pbrMetallicRoughness

### ISSUE THREAD

**Issue by Joos-OST** [syoyo/tinygltf#294]
**Describe the issue**

When serializing to GLTF, I sometimes have materials that have only set a `baseColorFactor` for `pbrMetallicRoughness` and nothing more. When the color is pure white (i.e. `1.0,1.0,1.0,1.0`) the material in the resulting `.gltf` file is `null`:

```
{
  "asset": {
    "generator": "TestGenerator",
    "version": "2.0"
  },
  "materials": [
    null
  ]
}

```

**To Reproduce**

- OS: Windows
- Compiler: Worked the same with any compiler I tried

The following code snippet will reproduce the issue with version 2.4.0:

```
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION

//#define TINYGLTF_NO_STB_IMAGE_WRITE

#ifndef TINYGLTF_NO_STB_IMAGE_WRITE
#define STB_IMAGE_WRITE_IMPLEMENTATION
#endif

#include "tiny_gltf.h"

void WriteFile(std::string filename, std::vector<double> baseColorFactor)
{
    tinygltf::Model m;

    tinygltf::Material mat;
    mat.pbrMetallicRoughness.baseColorFactor = baseColorFactor;
    m.materials.push_back(mat);

    tinygltf::TinyGLTF loader;
    loader.WriteGltfSceneToFile(&m, filename, false, false, true, false);
}

int main()
{
    WriteFile("faulty.gltf", {1.0, 1.0, 1.0, 1.0});
    WriteFile("valid.gltf", {1.0, 0.1, 1.0, 1.0});
    return 0;
}
```

**Expected behaviour**

I expect the file produced by the first line in `main` to produce the following gltf:

```
{
  "asset": {
    "generator": "TestGenerator",
    "version": "2.0"
  },
  "materials": [
    {
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          1.0,
          0.1,
          1.0,
          1.0
        ]
      }
    }
  ]
}
```

**Additional context**

I found that in [tiny_gltf.h](https://github.com/syoyo/tinygltf/blob/0543640a831abfb0be25e8261b4ecf0c3d56f136/tiny_gltf.h#L6816), the color is not serialized when it is the same as `default_baseColorFactor`. However, I would not expect it to write a `null` in the final `.json` file.

**Comment by syoyo** [comment]
Good catch!

It looks null output happens as a side effect of this fix: https://github.com/syoyo/tinygltf/issues/204

According to glTF validator, `null` object is not allowed for materials,

https://github.com/KhronosGroup/glTF-Validator

So we need to emit empty object(`{}`) instead of `null`.
 
Since `material` does not have any required parameters, empty JSON object is allowed.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#material

**Comment by Joos-OST** [comment]
Oh wow, that was a really quick response. Thank you so much 👍
