### ISSUE TITLE
tinygltf is not supported in a add_subdirectory context in cmake

### ISSUE THREAD

**Issue by Cazadorro** [syoyo/tinygltf#298]
**Describe the issue**

While tinygltf is a cmake project, I cannot currently use it in its default configuration as a project in a subdirectory.  This prohibits me from using tinygltf in a normal workflow with out modifying the CMake source.  

**To Reproduce**

- OS Any
- Compiler, compiler version, compile options Any

**Expected behaviour**

I expected a Cmake INTERFACE target to be created because this is a header only library, which I can use directly after using add_subdirectory(path_to_tinygltf), rather than having only availible with an install which is not appropriate for my development environment, and with out a target, which isn't appropriate for any cmake project.   This is what other libraries like GLM do, and funnily enough, even what one of this projects dependencies which is header only, nlohmann json does,  and is standard procedure for header only CMake projects.   

**Additional context**

I will provide what I personally did to get this project to work as a subproject (appended to the end of current CmakeList.txt), it's not extensively tested, and may rely on features newer than cmake 3.6.   This may not be the best solution for the project as whole.  This also includes an option for using a cpp provided by the library which I also created.  

```
option(TINYGLTF_CREATE_CPP "generate a cpp for you" OFF)
if(TINYGLTF_CREATE_CPP)
  add_library(tinygltf)
  target_sources(tinygltf PRIVATE
          tiny_gltf.cpp)
  target_include_directories(tinygltf
          INTERFACE
          $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
          $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
          )
else()
  add_library(tinygltf INTERFACE)

  target_include_directories(tinygltf
          INTERFACE
          $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
          $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
  )

endif()

```

CPP file (tiny_gltf.cpp

```
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION

#include "tiny_gltf.h"
```

**Comment by syoyo** [comment]
@Cazadorro current cmake  file is not designed to be used with `add_subdirectory`.  Thanks you for the proposal and some information(glm, nlohmann json). Let me give some time to review what is the best way to add support of `add_subdirectory` feature

**Comment by syoyo** [comment]
@Cazadorro I made a CMake script which is `add_subdirectory` friendly based on your comment. Please take a look:  https://github.com/syoyo/tinygltf/compare/cmake-add-subdirectory

**Comment by Cazadorro** [comment]
@syoyo Sorry for the long wait, I hadn't had a reason to use GLTF for a while, I just tried this today, it appears to do the job,

**Comment by syoyo** [comment]
@Cazadorro Good. PR will be created soon.

**Comment by bmahlbrand** [comment]
+1 for this feature

**Comment by syoyo** [comment]
@bmahlbrand Oh, I forgot to create a PR... Now merged!
