### ISSUE TITLE
Loading a gltf model file and converting to interleaved vertex buffer yields wrong index buffer

### ISSUE THREAD

**Issue by elad8a** [syoyo/tinygltf#300]
I think I have a problem interpreting the Mesh class data to a interleaved vertex buffer and drawing it via DrawIIndexed (directx).

I wrote a thorough explanation and simplified code in this[ SO question](https://stackoverflow.com/questions/65519948/loading-a-gltf-model-file-and-converting-to-interleaved-vertex-buffer-yields-wro).

Can someone please shed some light at what am I doing wrong?

![image](https://user-images.githubusercontent.com/17446835/103407614-eaec4700-4b67-11eb-8f3e-06e7ed0bb0c3.png)

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/issues/291
