### ISSUE TITLE
Accessors min/max are serialized as float for int accessors

### ISSUE THREAD

**Issue by AurL** [syoyo/tinygltf#301]
**Describe the issue**

All accessors min/max are serialized as double/float even it accessor refers to int values.
It raises the following validation warning:
```
{'code': 'INTEGER_WRITTEN_AS_FLOAT',
 'message': 'Integer value is written with fractional '
 'part: 25.0.',
 'pointer': '/accessors/149/max',
 'severity': 1},
```
(I might be missing something, sorry if it's the case).

**To Reproduce**

Create a glTF with accessors pointing to int values(indices for example), specify min/max, and then serialize.

**Expected behaviour**

Accessor type (int/float) is respected when serializing min/max values.

**Additional context**
It is "not an issue" when using the version with picojson since it seemed to convert `5.0` to `5` but It's not clear if the opposite was happening sometimes.
It seems to happen here in [json.hpp](https://github.com/syoyo/tinygltf/blob/master/json.hpp#L11488-L11543). 

Also these fields are optional (except for [POSITION](https://github.com/syoyo/tinygltf/blob/master/json.hpp#L11488-L11543) and [animation inputs](https://github.com/syoyo/tinygltf/blob/master/json.hpp#L11488-L11543)) so it's not a big deal, and it's possible to workaround by only serializing min/max for float accessors.

**Comment by syoyo** [comment]
@AurL Good issue!

So simply serializing `min/max` as integer when `componentType` has integer-type should solve the issue?
(if so, the fix can be soon provided)
 
https://github.com/syoyo/tinygltf/blob/f161782001bad1cd3c6c537d8bd033c642812156/tiny_gltf.h#L6624
