### ISSUE TITLE
The asset should be generated automatically if it was not explicitely set by the user

### ISSUE THREAD

**Issue by dov** [syoyo/tinygltf#308]
**Describe the issue**

A gltf file is invalid unless it has the the `asset` object defined. Since tiny_gltf always generates gltf version 2.0 files the valueois constant `model.asset.version="2.0"` . This value should be provided automatically be the library, if it was not set by the user.

**To Reproduce**

Modify the build-gltf example in the example directory, but and remove the assignment of the `asset` object. Inspect the gltf file (or send it to the khronos validator).  The resulting gltf file is missing the `asset` object.

**Expected behaviour**

Automatically provide the `asset` object unless it was specified by the user, when saving a file.

**Comment by syoyo** [comment]
@dov Thanks! Confirmed the issue.

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#asset-1

According to the spec, at least `model.asset.version` must exist.
