### ISSUE TITLE
FIXME: Fix CI build.

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinygltf#31]
Some configuration failed in TravisCI and AppVeyor.

**Comment by Ybalrid** [comment]
At least on the Travis side, it looks like one of the clang build is failing to install gcc. When I find some time tomorrow, I'll setup Travis and Appveyor on my side and tweak the yml file that confingure this. If I get them build cleanly (they should!) I'll send a PR

**Comment by syoyo** [comment]
Cool! > If I get them build cleanly (they should!) I'll send a PR

>  it looks like one of the clang build is failing to install gcc.

This would be a apt package problem(high bandwidth to apt package server)
It may be better to switch Docker-based build in Travis build.
 
Also, I can setup a bounty program for this issue.

Reward: 0.035 BCH(Bitcoin cash.  ~= $100 USD) (Only for the fist people who passes the acceptance test)
Requirement: Fixes & improves CI build(Travis and AppVeyor. clang, gcc and MSVC)
Acceptance test: Review PR and confirm CI build get normal.
Pay due date: As soon as the acceptance test has been passed.

**Comment by Ybalrid** [comment]
AppVeyor's build fails in json.hpp because of the noexept qualifiers.

The version of Visual Studio used in the AppVeyor configuration doesn't support C++11's "noexept" yet (cf this page on Microsoft documentation https://msdn.microsoft.com/en-us/library/hh567368.aspx)

**Comment by syoyo** [comment]
Here is the transaction FYI: https://blockchair.com/bitcoin-cash/address/qqw9rhpa9qvfx2pwu6g9k8npmk8uk3uzuc0v8xpjzp
