### ISSUE TITLE
tiny_gltf.h:1515:10: fatal error: json.hpp: No such file or directory

### ISSUE THREAD

**Issue by raul-physna** [syoyo/tinygltf#311]
**Describe the issue**
Program fails to compile when installing tiny_gltf using vcpkg

**To Reproduce**
- Ubuntu 18.04
- g++ 10.2.0

./vcpkg install tinygltf
Tried compiling simple .cpp that has `#include "tiny_gltf.h"`
Build fails with error message: 

```
[build] /opt/app/mojo/3rdparty/vcpkg/installed/x64-linux/include/tiny_gltf.h:1515:10: fatal error: json.hpp: No such file or directory
[build]  1515 | #include "json.hpp"
[build]       |          ^~~~~~~~~~
[build] compilation terminated.
```
**Expected behaviour**

Compilation should succeed.
 
I edited the tiny_gltf.h (line 1515) from
`#include "json.hpp"`
to:
`#include "nlohmann/json.hpp"`

and everything worked

**Screenshots**

![image](https://user-images.githubusercontent.com/64029409/110588947-b8e8f980-8143-11eb-9b5b-9c57e56e391e.png)

**Additional context**

**Comment by syoyo** [comment]
Please post an issue to vcpkg project, not here.

And it is highly recommended not to use tinygltf through vcpkg

**Comment by raul-physna** [comment]
Thank you, @syoyo
