### ISSUE TITLE
LoadBinaryFromMemory doesnt load binary asset 

### ISSUE THREAD

**Issue by amarav** [syoyo/tinygltf#315]
Hi,

I'm not sure what basedir means in LoadBinaryFromMemory.
I pass a valid buffer and buffer size to this interface but it doesnt load the asset.

Can anyone help in usage of this interface?

**Comment by amarav** [comment]
@syoyo Could you give some inputs to resolve the issue? What is base dir in this?

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/issues/291
