### ISSUE TITLE
LoadBinaryFromMemory doesnt return proper loaded asset 

### ISSUE THREAD

**Issue by amarav** [syoyo/tinygltf#316]
**Describe the issue**

LoadBinaryFromMemory doesnt return proper loaded asset 

**To Reproduce**

- C++ application 
- Windows
- Using unzipped glb file from https://rendercore.s3.ap-south-1.amazonaws.com/text_rendering.glb.gz 

Pass this buffer to LoadBinaryFromMemory and expected to return a valid asset

**Expected behaviour**

Expected to load the buffer from the glb and return the asset from LoadBinaryFromMemory 

**Screenshots**

Snippet:
  
        tinygltf::Model* model;
        {
            model = new tinygltf::Model();
        }
        tinygltf::TinyGLTF gltf_ctx;
        ret = gltf_ctx.LoadBinaryFromMemory(model, &err,0,(const unsigned char *)fl_rawbytes,buffer_length,"",0x3f);

Here fl_rawbytes is the buffer i pass and code throws exception within LoadBinaryFromMemory and program exits

**Comment by syoyo** [comment]
@amarav You should provide minimal reproducible test code.

At least following code successfully loads .glb.

```c++
  tinygltf::Model model;
  tinygltf::TinyGLTF ctx;
  std::string err;
  std::string warn;

  std::ifstream file("./text_rendering.glb");
  REQUIRE_FALSE(!file);

  file.seekg(0, file.end);
  size_t sz = static_cast<size_t>(file.tellg());
  file.seekg(0, file.beg);

  std::vector<uint8_t> buf(sz);

  file.read(reinterpret_cast<char *>(buf.data()), static_cast<std::streamsize>(sz));

  bool ret = ctx.LoadBinaryFromMemory(&model, &err, &warn, buf.data(), buf.size());
```
