### ISSUE TITLE
Not assigned skeleton property is saved as -1

### ISSUE THREAD

**Issue by Alexeyt89** [syoyo/tinygltf#321]
**Describe the issue**
If skeleton node index is not set for skin, it is exported as "skeleton": -1
-1 is not described in gltf spec as possible valid value. It might lead to exceptions in some importers. 

**Expected behaviour**
The standard allows not to have the skeleton property in skins.
I suggest that instead of writing -1 the property should not be added at all.
Something like this could be done to fix this problem:
`if(skin.skeleton != -1)
    SerializeNumberProperty("skeleton", skin.skeleton, o);`

There are examples which don't have skeleton nodes at all and the property can't be set to a valid value. SimpleSkin, for instance, has 2 root joint nodes used by the model's skin.

**Comment by syoyo** [comment]
@Alexeyt89 Thanks! 

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#skin

`skeleton` is optional and its value should be zero or positive integer if `skeleton` is provided.

**Comment by syoyo** [comment]
Here is a fix: https://github.com/syoyo/tinygltf/commit/d07b976d59b053eaf12539c474f4f94243985b84

@Alexeyt89 Do you have minimal .gltf(or C++ code) to reproduce the issue? I'd like to add it to unit test suite.

**Comment by Alexeyt89** [comment]
[text.zip](https://github.com/syoyo/tinygltf/files/6391094/text.zip)
I'm adding gltf support to a pretty huge project and I don't see an easy way to create minimal c++ example out of it.
Here is an example created with tinygltf. To open it in blender the ""skeleton": -1" should be removed from the file.

**Comment by Alexeyt89** [comment]
@syoyo, Thanks, I checked the fix and it works.

**Comment by syoyo** [comment]
@Alexeyt89 Awesome! Thanks! I will check test scene you provided and then create PR soon.

**Comment by syoyo** [comment]
Added regression test https://github.com/syoyo/tinygltf/pull/322/files and merged the fix.

@Alexeyt89 Thank you for the support!
