### ISSUE TITLE
Accessors without bufferviews can't be loaded

### ISSUE THREAD

**Issue by Alexeyt89** [syoyo/tinygltf#324]
**Describe the issue**
Models can't be loaded if they have accessors without bufferviews

**To Reproduce**
Some models, like this:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Lantern/glTF-Draco/Lantern.gltf
have only accessors without bufferviews. In parsing of the accessors the bufferview index is set to -1. 
The loading process interrupts with error: "accessor[0] invalid bufferView"

Loading stack:
1) tinhygltf::TinyGLTF::LoadASCIIFromFile
1) tinhygltf::TinyGLTF::LoadASCIIFromString
1) tinhygltf::TinyGLTF::LoadFromString <- here it stops at line 5757

Draco verison 1.4.1

**Comment by syoyo** [comment]
You need to describe issue more precisely(e.g. compile options) and also need to attach minimal reproducible code

**Comment by Alexeyt89** [comment]
[tinygltftest.zip](https://github.com/syoyo/tinygltf/files/6454690/tinygltftest.zip)
To reproduce:
1) correct the path to the model in main.cpp (the model is included)
2) build and run the example.
The problem is reproducible in Qt 6.0.0 with compilers MSVC2019 64b, MinGW64b and it is reproducible if the project is built in Visual Studio 2019.
Also I tested all the other Khronos Group example models with draco compression, none of them can be loaded.
