### ISSUE TITLE
Suspecting gltf parsing issue  

### ISSUE THREAD

**Issue by pcarret** [syoyo/tinygltf#335]
**Describe the issue**

I'm experementing  https://github.com/BobLChen/PathTracer which use tinygltf to import meshes and materials
The "same" 3D content file depending if it's based on glb or gltf format produce

**To Reproduce**
Open 2.gltf and 2.glb with a gltf viewer using tinygltf
[assets.zip](https://github.com/syoyo/tinygltf/files/7486728/assets.zip)

Boths file scan be opened correctly with Microsoft Windows 10 Viewer :
![image](https://user-images.githubusercontent.com/7167627/140528285-7730ba17-5851-4d06-8bd2-46817f7b25f4.png)

**Expected behaviour**
Results should be identical

**Screenshots**
Reuslt are very different. I suspect a bad/shift indexing during gltf parsing. It results in a very weird mesh
There is maybe one mesh without dat alike normals or texture coords and this create an unexcepectde behavior

![image](https://user-images.githubusercontent.com/7167627/140519499-29505b05-2b88-452b-acf6-be1b82fa0d18.png)

![image](https://user-images.githubusercontent.com/7167627/140519615-3f9758b7-d4de-491d-87d8-3a2bb16f9861.png)

**Additional context**
glview can open glb but not gltf sample

![image](https://user-images.githubusercontent.com/7167627/140527386-0766b397-1665-47c8-874d-9b93561861ee.png)

**Comment by syoyo** [comment]
`2.gltf`  can be read in `glview` (no shading though)

<img width="721" alt="Screen Shot 2021-11-06 at 2 25 53" src="https://user-images.githubusercontent.com/18676/140553094-138be1b9-e578-4f69-a618-6ccc0e1e20b3.png">

You need to file an issue at `BobLChen/PathTracer`, not here.
