### ISSUE TITLE
Can't open VRM files

### ISSUE THREAD

**Issue by disks86** [syoyo/tinygltf#336]
**Describe the issue**

When opening VRM files with "LoadASCIIFromFile" it returns an error message of "Root element is not a JSON object" when using rapidjson or "[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'g'" when using the default json parser.

**To Reproduce**

Tested on Windows with the attached gltf file.
[Main.zip](https://github.com/syoyo/tinygltf/files/7535557/Main.zip)

**Expected behaviour**

Although this library doesn't advertise support for VRM I would expect it to still be able to read the elements not related to the extension as it is possible to open these files in GLTF viewers such as https://gltf-viewer.donmccurdy.com/

**Comment by Radagan** [comment]
I'm getting this error from an FBX conversion I did in Blender to save the file as glTF 2.0 (glb). Did you resolve this error?

**Comment by disks86** [comment]
> I'm getting this error from an FBX conversion I did in Blender to save the file as glTF 2.0 (glb). Did you resolve this error?

It's been a while back but I believe I gave up and switched to the binary version of GLTF (glb).

**Comment by Radagan** [comment]
@disks86 Thanks! That's exactly what I was mistakenly trying to do.
