### ISSUE TITLE
Typo in Sampler::operator==  ?

### ISSUE THREAD

**Issue by epajarre** [syoyo/tinygltf#343]
**Describe the issue**

I decided to update my tinygltf version and while comparing the differences I noticed that
wrapS is not checked when doing Sampler::operator==

The current code is as follows:

```
bool Sampler::operator==(const Sampler &other) const {
  return this->extensions == other.extensions && this->extras == other.extras &&
         this->magFilter == other.magFilter &&
         this->minFilter == other.minFilter && this->name == other.name &&
         this->wrapT == other.wrapT;

         //this->wrapR == other.wrapR && this->wrapS == other.wrapS &&
}
```
Am I missing something or was the wrapS removed incorrectly when wrapR was removed?

**To Reproduce**

Issue noticed by looking at source code

**Expected behaviour**

wrapS should also be checked

**Screenshots**

no screenshots

**Additional context**

**Comment by syoyo** [comment]
@epajarre Good find! Just forget to uncomment  `wrapS` ... Fix is easy, but your PR contribution is much appreciated!

**Comment by epajarre** [comment]
Not really experienced with this, but tried to create  pull request, The automatic checks for MSVC failed but it looks like a generic cmake problem.

**Comment by syoyo** [comment]
@epajarre Thanks! :pray: Yes we can ignore MSVC build issue(CI setup failure)
