### ISSUE TITLE
examples / glview has rotation errors

### ISSUE THREAD

**Issue by tsmaster** [syoyo/tinygltf#348]
**Describe the issue**

in examples/glview, Rotated children are not rotated or positioned correctly

**To Reproduce**

- OS : Ubuntu Linux
- Compiler, compiler version, compile options (as default in the makefile)
- Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data

Tested with raceFuture.glb from https://www.kenney.nl/assets/car-kit

**Expected behaviour**

the wheels of the vehicles properly face outwards from the correct positions

**Screenshots**

Wrong:
![image](https://user-images.githubusercontent.com/72338/156033322-ac723bf2-a001-4ee6-a20a-8c3a931ece4f.png)

Fixed:
![image](https://user-images.githubusercontent.com/72338/156033459-e68a7551-2335-489f-850f-dd3eac1e1dab.png)

**Additional context**
It looks to me like the rotation value (4 doubles), which is defined to be a normalized quaternion, is being passed to glRotated, which is an angle (in degrees(!)) around an axis. Also, the rotation and translation seems backwards.

**Comment by syoyo** [comment]
@tsmaster Thanks! Confirmed the issue on my side. 

> It looks to me like the rotation value (4 doubles), which is defined to be a normalized quaternion, is being passed to glRotated,

https://github.com/syoyo/tinygltf/blob/a1952053eeb566c612499f36172a84653e0611fe/examples/glview/glview.cc#L789

Yes, quarternion value is passed to glRotated(which takes angle + rotation axis)...

Could you please send PR of your fix?

**Comment by tsmaster** [comment]
PR submitted

**Comment by syoyo** [comment]
@tsmaster Thanks! Close this issue via https://github.com/syoyo/tinygltf/pull/349
