### ISSUE TITLE
Failed validation from https://github.khronos.org/glTF-Validator/

### ISSUE THREAD

**Issue by leviskim17** [syoyo/tinygltf#351]
**Describe the issue**

When I tried to have a validation with the khronous glTF-Validator, I have these errors and a warning. May I know how to approach to fix these? 

It is the result of validation.

`
{
    "uri": "SampleProjectFeet_000.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.3.4",
    "validatedAt": "2022-03-03T05:44:19.776Z",
    "issues": {
        "numErrors": 2,
        "numWarnings": 1,
        "numInfos": 0,
        "numHints": 0,
        "messages": [
            {
                "code": "VALUE_NOT_IN_LIST",
                "message": "Invalid value 5130. Valid values are (5120, 5121, 5122, 5123, 5125, 5126).",
                "severity": 1,
                "pointer": "/accessors/0/componentType"
            },
            {
                "code": "MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS",
                "message": "accessor.min and accessor.max must be defined for POSITION attribute accessor.",
                "severity": 0,
                "pointer": "/meshes/0/primitives/0/attributes/POSITION"
            },
            {
                "code": "MESH_PRIMITIVE_ATTRIBUTES_ACCESSOR_INVALID_FORMAT",
                "message": "Invalid accessor format '{VEC3, null}' for this attribute semantic. Must be one of ('{VEC3, FLOAT}').",
                "severity": 0,
                "pointer": "/meshes/0/primitives/0/attributes/POSITION"
            }
        ],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "tinygltf",
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "data-uri",
                "byteLength": 462501
            }
        ],
        "animationCount": 0,
        "materialCount": 1,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": false,
        "hasDefaultScene": false,
        "drawCallCount": 1,
        "totalVertexCount": 35577,
        "totalTriangleCount": 0,
        "maxUVs": 0,
        "maxInfluences": 0,
        "maxAttributes": 1
    }
}
`

it is my source code to generate the gltf linked up the upper result. It is referred one of the example from here.

        tinygltf::Model model;
        tinygltf::Scene scene;
        tinygltf::Mesh mesh;
        tinygltf::Primitive primitive;
        tinygltf::Node node;
        tinygltf::Buffer buffer;
        tinygltf::BufferView bufferView0;
        tinygltf::Accessor accessor0;
        tinygltf::Asset asset;

        asset.version = "2.0";
        asset.generator = "tinygltf";

        std::cout << "positions.size(): " << positions.size() << std::endl;
        std::cout << "byte_size(positions): " << byte_size(positions) << std::endl;
        std::cout << "byte.size(): " << byte_size(positions) / positions.size() << std::endl;

        std::cout << "normals.size(): " << normals.size() << std::endl;
        std::cout << "byte_size(normals) " << byte_size(normals) << std::endl;
        std::cout << "byte.size(): " << byte_size(normals) / normals.size() << std::endl;

        std::cout << "colors.size(): " << colors.size() << std::endl;
        std::cout << "byte_size(colors): " << byte_size(colors) << std::endl;
        std::cout << "byte.size(): " << byte_size(colors) / colors.size() << std::endl;

        std::cout << "Full data size: "  << positions.size() + normals.size() + colors.size() << std::endl;
        std::cout << "Full byte size: " << byte_size(positions) + byte_size(normals) + byte_size(colors) << std::endl;
        std::cout << "Full data_buffer size: " << data_buffer.size() << std::endl;

        // raw data buffer. 
        buffer.data = data_buffer;

        bufferView0.buffer = 0;
        bufferView0.byteOffset = 0;
        bufferView0.byteLength = byte_size(positions);
        std::cout << "bufferView0.byteLength: " << bufferView0.byteLength << std::endl;
        std::cout << "byte_size(positions): " << byte_size(positions) << std::endl;
        bufferView0.target = TINYGLTF_TARGET_ARRAY_BUFFER;

        accessor0.bufferView = 0;
        accessor0.byteOffset = 0;
        accessor0.componentType = TINYGLTF_COMPONENT_TYPE_DOUBLE;
        accessor0.count = positions.size();
        accessor0.type = TINYGLTF_TYPE_VEC3;
        std::cout << "pos_max_x, pos_max_y, pos_max_z: " << pos_max[0] << ", " << pos_max[1] << ", " << pos_max[2] << std::endl;
        std::cout << "pos_min_x, pos_min_y, pos_min_z: " << pos_min[0] << ", " << pos_min[1] << ", " << pos_min[2] << std::endl;
        accessor0.maxValues = { pos_max[0], pos_max[1], pos_max[2] };
        accessor0.minValues = { pos_min[0], pos_min[1], pos_min[2] };
        accessor0.name = "POSITION";

        primitive.attributes["POSITION"] = 0;  // The index of the accessor for positions
        primitive.material = 0;
        primitive.mode = TINYGLTF_MODE_POINTS; // need to find the meaning of enum
        mesh.primitives.push_back(primitive); // add it to the mesh

        node.mesh = 0;
        scene.nodes.push_back(0); // Default scene

        model.scenes.push_back(scene);
        model.meshes.push_back(mesh);
        model.nodes.push_back(node);
        model.buffers.push_back(buffer);
        model.bufferViews.push_back(bufferView0);
        model.accessors.push_back(accessor0);
        model.asset = asset;

        tinygltf::Material mat;
        mat.pbrMetallicRoughness.baseColorFactor = { 1.0f, 0.9f, 0.9f, 1.0f };
        mat.doubleSided = true;
        model.materials.push_back(mat);

        tinygltf::TinyGLTF gltf;
        gltf.WriteGltfSceneToFile(&model, outputpath.string(),
            true, // embedImages
            true, // embedBuffers
            true, // pretty print
            false); // write binary

        return true;
'

Firstly, the part I don't understand is Invalid value 5130. I input double values and configured TINYGLTF_COMPONENT_TYPE_DOUBLE. May I know what I missed? 

**To Reproduce**
N/A

- OS: Windows 10
- Compiler, compiler version, compile options: VS 2019 64bit

**Expected behaviour**

N/A

**Screenshots**

N/A

**Additional context**|

The capture of log

![capture for printf](https://user-images.githubusercontent.com/10830535/156507228-770de20f-cc74-4c43-bb50-8939364aba4f.PNG)

**Comment by syoyo** [comment]
componentType `DOUBLE` is not supported in glTF 2.0 spec. You should not use it if you want your model glTF 2.0 confirmant.

**Comment by syoyo** [comment]
FYI Added a comment about `DOUBLE` type here: https://github.com/syoyo/tinygltf/commit/6ed7c39d71b81b1454238c72dd2d3c3380c8ef36
