### ISSUE TITLE
Incompatibility with Win API or some options... (Visual Studio 2022)

### ISSUE THREAD

**Issue by unit-a-user** [syoyo/tinygltf#355]
I tried to load GLTF file, but always getting error... 
```
Exception thrown at 0x00007FF87497358C (KernelBase.dll) in ZEON.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

```cpp
  tinygltf::Model model;
  tinygltf::TinyGLTF loader;
  std::string err = "";
  std::string warn = "";

  bool ret = loader.LoadASCIIFromFile(&model, &err, &warn, "BoomBox.gltf");
```

I don't know why. Probably because Windows 11, Visual Studio 2022, and default string formats incompatible by current WinAPI. Probably because I set env `ASAN_OPTIONS=windows_hook_legacy_allocators=true` (but I tried to disable address sanitizer, but got same error), or probably I used future C++ versions... but I think problem with incorrect string lengths...

**Comment by syoyo** [comment]
You need to attach minimal & reproducible procedure(source code, cmake setting, .sln, etc.)
