### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by MarioSieg** [syoyo/tinygltf#356]
Is it safe to load gltf models from a different thread
when each thread has it's own tinygltf::TinyGLTF instance or are there internally
global variables which are not synced?

Also what would you think about a JSON backend using SIMDJson? Might speed up the load time significantly...

Best Regards,

Mario

**Comment by syoyo** [comment]
It may depend on JSON backend: https://github.com/syoyo/tinygltf/issues/241

You can contribute SIMDJson backend! PR is much appreciated.

**Comment by MarioSieg** [comment]
Okay thanks!
I will benchmark my loading performance and if there is need for faster parse I'll write a branch with SIMDJson!
