### ISSUE TITLE
Wrong index size

### ISSUE THREAD

**Issue by ibaris** [syoyo/tinygltf#361]
**Describe the issue**

I created a simple panel with four coordinates:

![image](https://user-images.githubusercontent.com/15630368/174278542-0e61b1e9-2175-4ce7-adcf-59f780248490.png)

After the triangulation, the indices should contain 2 rows with 3 numbers, which refers to the position of the vertices:

```
index 1: 0, 1, 3
index 2: 0, 3, 2
```

But that what I get has 6 entries that look like this:
```
index 1: 0, 1, 3
index 2: 0, 3, 2
index 3: 65021, 65021, 26144
index 4: 32567, 542, 0
index 5: 27696, 32567, 542
index 6: 0, 0, 0
```
The first two entries are correct. But what do the remaining 4 mean?

**To Reproduce**

- Windows 10
- Visual Studio 2022
- [plate_1x1.zip](https://github.com/syoyo/tinygltf/files/8926658/plate_1x1.zip)

```cpp
#define TINYGLTF_IMPLEMENTATION
#if defined(WIN32)
#pragma warning(push)
#pragma warning(disable : 4267)
#endif
#include <lib/tinygltf/tiny_gltf.h>

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <lib/tinygltf/stb_image_write.h>

int main(const std::string &input_string)
{
    tinygltf::Model gltf_model;
    tinygltf::TinyGLTF loader;
    std::string err;
    std::string warn;

    bool ret = loader.LoadBinaryFromFile(&gltf_model, &err, &warn, input_string);

    const auto &gltf_mesh = gltf_model.meshes[gltf_model.nodes[0].mesh];

    for (size_t i = 0; i < gltf_mesh.primitives.size(); i++)
    {
        auto primitive = gltf_mesh.primitives[i];

        accessor = gltf_model.accessors[primitive.indices];
        bufferView = gltf_model.bufferViews[accessor.bufferView];
        buffer = gltf_model.buffers[bufferView.buffer];

        auto *index = reinterpret_cast<const uint16_t *>(&buffer.data[bufferView.byteOffset + accessor.byteOffset]);

        for (size_t j = 0; j < accessor.count; ++j)
        {
            int x = index[j * 3 + 0];
            int y = index[j * 3 + 1];
            int z = index[j * 3 + 2];

            printf("%i, %i, %i\n", x, y, z);
        }
    }
    
    return 0;
}           
```

*Note*: The `accessor` has a `count` attribute, which stores the value `6`. I think, this should be `2` instead.

**Comment by syoyo** [comment]
`6 / 3(triangle) = 2(faces)` so nothing will be wrong. 

glviewer example shows the plane correctly.

![Screenshot from 2022-06-17 19-52-31](https://user-images.githubusercontent.com/18676/174284705-bf3ed32f-6afb-4843-80cb-81871dfb41f0.png)

You need to study how to handle glTF data through glview https://github.com/syoyo/tinygltf/blob/master/examples/glview/glview.cc or other glTF example code.

**Comment by ibaris** [comment]
Thank you for your fast reply! Just because it is displayed correctly, I would still like to understand what is happening there. Therefore, I would be very happy if you could help me with your expertise to understand the *problem*. 

In the example I can not see how the `glview.cc` handles the indices correctly. Where is the *magic* happening? Maybe [here](https://github.com/syoyo/tinygltf/blob/b901dd62d88f3c68bd498354c8aa215b1a7269c5/examples/glview/glview.cc#L699) somewhere?
