### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [syoyo/tinygltf#370]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@pyraun) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by syoyo** [comment]
https://github.com/syoyo/tinygltf/issues/291

**Comment by JamieSlome** [comment]
@syoyo - I have updated the contents of this issue, can we re-open it?

**Comment by syoyo** [comment]
You need to post minimal reproducible code and dataset if you find an issue.

example: https://github.com/syoyo/tinyexr/issues/169

**Comment by JamieSlome** [comment]
I see :)

Are you happy for me to share both vulnerabilities in separate GitHub Issues?
