### ISSUE TITLE
Extract Joint Names?

### ISSUE THREAD

**Issue by kklouzal** [syoyo/tinygltf#371]
I am using [TinyGLTF](https://github.com/syoyo/tinygltf) to import GLTF files into my application and am in need of reading out the names of joints. I can pull indices and weights just fine, but do not see a straightforward way to pull the (string/char) name of each joint.

Page 5 of the [gltf20-reference-guide](https://extension//elhekieabhbkpmcefcoobjddigjcaadp/https://www.khronos.org/files/gltf20-reference-guide.pdf) appears to show that joint names are present inside a GLTF file, but does a poor job of explaining which accessor to use etc..

Is this possible?

**Comment by syoyo** [comment]
glTF itself has poor definition of Skinning feature and TinyGLTF also does not provide any helper functions for (easy) handling of Skinning hierarchy. 

Probably you need to write your own scene traversal routine to get joint names, but still, you could only extract name of node as a joint name from glTF(if your glTF does not contain any extensions/extra data for Skinning).

Probably related issues in glTF:


https://github.com/KhronosGroup/glTF/issues/1665
https://github.com/KhronosGroup/glTF/issues/1270

**Comment by kklouzal** [comment]
Yes, a simple name is all that's required. This way I can pair the joint id with it's name for use elsewhere in my application.

I've tried a few different ways to try and extract the nodes name (I know it exists within the gltf file), but I cannot for the life of me find any way to pull it out.. Any clues?

Thank you.

**Comment by kklouzal** [comment]
You are correct, the name is only stored in the node and the joint id's are only stored in the skin.
There seems to be no way to connect these two and link a node to a joint to grab it's name.
Unless I'm missing something....

**Comment by kklouzal** [comment]
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.pdf
Section 3.7.3.2. Joint Hierarchy:

> The joint hierarchy used for controlling skinned mesh pose is simply the node hierarchy, with each node designated as a joint by a reference from the skin.joints array
Which, from what I understand, means a skins joint id == node id.
```
for (size_t i = 0; i < model.skins.size(); i++)
{
    tinygltf::Skin _Skin = model.skins[i];

    for (auto& JointID : _Skin.joints)
    {
        std::string NodeName = model.nodes[JointID].name;
        int ID = JointID - _Skin.skeleton;
    }
}
```
Subtract `_Skin.skeleton` from each `JointID` in the event our skeleton root node is greater than 0. If you don't do this then your joint ID's will be skewed and won't match up with the inverse bind matrices.
