### ISSUE TITLE
[Question] Initial translation, rotation, and scale

### ISSUE THREAD

**Issue by Radagan** [syoyo/tinygltf#375]
I feel like I'm missing something very basic. In the Three.js glTF loader for javascript there's a property on scene where you can simply set a position, rotation and scale for the loaded model. I can't seem to find a way to do this in tinygltf even with good Vulkan examples. I am able to apply a translation that works using the following code, but the scale and rotation adjustments cause the model to fragment where nodes are offset incorrectly. 

It seems like such a simple thing everyone would need to do as they load glTF objects. Am I over complicating this? Looping recursively through all nodes kinda makes me feel like I am. 

When I drawNode, I call adjust on each nodeMatrix that was loaded by tinygltf. This applies a translation, rotation, and scale with the goal of effecting the entire model. As I want to be able to move the objects, these TRS values are passed each frame. 

Note: translation, rotation, and scale are members that hold the current world coordinate system value desired, and module_* are the values that the glTF file loaded. 

```C++
     glm::mat4 bare_gltf_loading_model::adjust(glm::mat4 matrix) {
        glm::vec3 pos = matrix[3];

        glm::vec3 module_scale{1.0,1.0,1.0};
        for(int i = 0; i < 3; i++)
            module_scale[i] = glm::length(glm::vec3(matrix[i]));

        const glm::mat3 rot_mtx(
            glm::vec3(matrix[0]) / module_scale[0],
            glm::vec3(matrix[1]) / module_scale[1],
            glm::vec3(matrix[2]) / module_scale[2]);
        glm::quat model_rot = glm::quat_cast(rot_mtx);
        model_rot = glm::conjugate(model_rot);
        pos += translation;

        auto adj_matrix = glm::mat4(1.0f);
        adj_matrix = glm::translate(adj_matrix, pos);
        adj_matrix *= glm::mat4(model_rot);
        adj_matrix *= glm::mat4(rotation);
        adj_matrix = glm::scale(adj_matrix, module_scale);
        adj_matrix = glm::scale(adj_matrix, scale);
        return std::move(adj_matrix);
    }
```

Any and all advice most welcome!

**Comment by syoyo** [comment]
Its not related to tinygltf. You should ask your glTF question to glTF community: https://github.com/KhronosGroup/glTF
