### ISSUE TITLE
Invalid bufferview

### ISSUE THREAD

**Issue by mgerhardy** [syoyo/tinygltf#378]
**Describe the issue**

`glTF-Sample-Models/2.0/RiggedFigure/glTF-Draco/RiggedFigure.gltf` can't get loaded (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure/glTF-Draco)

The error message from tinygltf is `accessor[77] invalid bufferView`

**To Reproduce**

- Linux
- clang
- https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure/glTF-Draco

**Expected behaviour**

I would expect this model to be loadable - especially because it's in the official KhronosGroup repository.

**Screenshots**

NA

**Additional context**

Source code where the tinygltf lib is used and the problem occurred with: https://github.com/mgerhardy/vengi/blob/master/src/modules/voxelformat/GLTFFormat.cpp

**Comment by syoyo** [comment]
You need to build tinygltf with Draco support

```
g++  -I../draco/src/ -I../draco/build -DTINYGLTF_ENABLE_DRACO -L../draco/build -std=c++11 -g -O0 -o loader_example loader_example.cc -L../draco/build/ -ldracodec -ldraco

./loader_example /path/to/glTF-Sample-Models/2.0/RiggedFigure/glTF-Draco/RiggedFigure.gltf
Reading ASCII glTF
=== Dump glTF ===
asset.copyright          : 
asset.generator          : COLLADA2GLTF
asset.version            : 2.0
asset.minVersion         : 
...
```

Contributing better error reporting is much appreciated.
