### ISSUE TITLE
Latest release version?

### ISSUE THREAD

**Issue by moritz-h** [syoyo/tinygltf#384]
Are the latest commits meant as new release version? I see references in the commit messages to v2.6.2 (eec4c98862b7fb760b2fb70971d7b652e593af9f) and v2.6.1 (4581d37bec66daeaccb869505c3e415c3179e9cd), but the newest tag is only 2.5.0. Are there git tags missing, or are this internal or hidden versions intentionally?

**Comment by syoyo** [comment]
You can grab the latest version from master branch and no strict version management/tagging exists for tinygltf at the moment. No internal and hidden version exists for tinygltf.
