### ISSUE TITLE
Byte length from buffer view is not equal to byte stride * accessor.count

### ISSUE THREAD

**Issue by vocasle** [syoyo/tinygltf#387]
**Describe the issue**
      
      const auto &accessor = model.accessors[accessorIdx];
      const auto &bufferView = model.bufferViews[accessor.bufferView];
      const auto &buffer = model.buffers[bufferView.buffer];
      const size_t byteStride = accessor.ByteStride(bufferView);
      assert(bufferView.byteLength == byteStride * accessor.count);

Last line triggers assert.

**To Reproduce**

- Windows 10 Pro Version 21H2 (OS Build 19044.2130)
- Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x86
- https://github.com/KhronosGroup/glTF-Sample-Models/blob/8e9a5a6ad1a2790e2333e3eb48a1ee39f9e0e31b/2.0/Box/glTF/Box.gltf

**Expected behaviour**

      assert(bufferView.byteLength == byteStride * accessor.count);

Should not assert.

**Comment by syoyo** [comment]
Current tiny_gltf.h https://github.com/syoyo/tinygltf/blob/release/tiny_gltf.h does not contain such line:

```
assert(bufferView.byteLength == byteStride * accessor.count);
```

You may need to update tinygltf.

**Comment by vocasle** [comment]
Well this code is not from tinygltf.

This is my code that replicates what is shown in [one of your examples](https://github.com/syoyo/tinygltf/blob/091a1fcc1abcef17c58bbbf400e85f5b87952491/examples/basic/main.cpp#L42).

My question was why BufferView::byteLength is not equal to Accessor::ByteStride multiplied by Accessor::count?
Is it expected?

**Comment by syoyo** [comment]
> My question was why BufferView::byteLength is not equal to Accessor::ByteStride multiplied by Accessor::count?

Its not related to tinygltf.

You need to check glTF 2.0 spec: https://github.com/KhronosGroup/glTF
