### ISSUE TITLE
Is there a way to validate the GLTF model before taking it for processing?

### ISSUE THREAD

**Issue by GasimGasimzada** [syoyo/tinygltf#400]
I would like to know if there is a way to validate the file for both invalid property values and for values that are not valid according to spec. For example, pointing mesh primitive attribute to a non existent accessor or checking if component type for position is always `FLOAT`.

**Comment by syoyo** [comment]
glTF itself is a JSON file(except for GLB binary), so you can use any JSON library to validate glTF syntax.

Here is an example: https://github.com/syoyo/tinygltf/tree/release/examples/validator

> pointing mesh primitive attribute to a non existent accessor 

This may be possible to validate using https://github.com/KhronosGroup/glTF-Validator
