### ISSUE TITLE
Option to disable automatic image loading

### ISSUE THREAD

**Issue by W4RH4WK** [syoyo/tinygltf#402]
Currently tinygltf only supports loading images via stb_image. While it is possible to hook a custom image loader into the loading process, I'd rather load images by myself using just the URI from the (ASCII) GLTF file.

It'd be nice to have an option to disable the automatic loading of images (without emitting any warnings).
All I need is the URI from the JSON file.

When setting `TINYGLTF_NO_STB_IMAGE`, a custom image loader _must_ be provided, otherwise the loader errors out.

Related #172

**Comment by syoyo** [comment]
@W4RH4WK Yeah! it should be nice to have.

Controlling Image loading will be implemented like:

* Add `disable_image_load` option to LoadImageDataOption https://github.com/syoyo/tinygltf/blob/52b73c7f0b41c54cc7f28cbf62598e6ca7d8e255/tiny_gltf.h#L1806
* Add `SetDisableImageLoad` API to TinyGLTF like this https://github.com/syoyo/tinygltf/blob/52b73c7f0b41c54cc7f28cbf62598e6ca7d8e255/tiny_gltf.h#L1471
* Additionally, for `TINYGLTF_NO_STB_IMAGE` case, we may better to provide no-op image loader fallback(with warning message)  when custom image loader is not set.

Your contribution is much appreciated!

**Comment by W4RH4WK** [comment]
While going through the code, I've found `TINYGLTF_NO_EXTERNAL_IMAGE`. It seems like this does exactly what I need.
