### ISSUE TITLE
Get String value from a tinygltf::Value object

### ISSUE THREAD

**Issue by soodsumil** [syoyo/tinygltf#403]
I want to know how to retrieve String type value from a tinygltf::Value object. I am able to get Integer and Double values by using GetNumberAsDouble() method but there seems to be no way to retrieve a String type value from this object.

**Comment by syoyo** [comment]
You should look at loader_example.cc 

https://github.com/syoyo/tinygltf/blob/52b73c7f0b41c54cc7f28cbf62598e6ca7d8e255/loader_example.cc#L248
