### ISSUE TITLE
How to show 2 models? (based on examples\basic)

### ISSUE THREAD

**Issue by oUp2Uo** [syoyo/tinygltf#413]
**Describe the issue**

**examples\basic** shows how to load and show 1 gltf model.
But when I try to edit the example to load 2 models at the same time, it didn't go well.
And also, I tried to load a texture as background before rendering the model, the model would go all black.

I guess the reason is that texture is not binded before draw model in main loop for 2 model.
(Texture is binded in `bindModel` which before the loop.)

I am a beginner OpenGL, and I tried to search this but have no answer.
I also have checked other samples like **examples\glview**, which has no texture.
Is there any sample to show how to render multi models?

Thank you.

**To Reproduce**

- OS : Win10
- Compiler, compiler version, compile options : VS2017
- Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data : models in **models** folder

**Expected behaviour**

A sample program which can show multi models.

**Comment by syoyo** [comment]
> Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data : models in models folder
