### ISSUE TITLE
Question about the (internal) parser signature

### ISSUE THREAD

**Issue by agnat** [syoyo/tinygltf#428]
Hi @syoyo,

after working with the code for a bit I have a question regarding the internals. While the serialiser uses a const and a non-const reference for in- and output, the parser uses a pointer. This seems a bit odd. What was the intended purpose here?

I'm asking because only the low-level functions perform a nullptr check and the high-level functions don't. I'm thinking about replacing the pointer with a writable reference, because that's much safer, obviously. What do you think?

Best...

**Comment by syoyo** [comment]
You should describe your question in detail, following https://github.com/syoyo/tinygltf/issues/291
