### ISSUE TITLE
Inclusion of third-party libraries causes conflicts

### ISSUE THREAD

**Issue by dyollb** [syoyo/tinygltf#432]
**Describe the issue**

Thanks for providing this library. Nice!

You include json.hpp and stb-image. In our setup we also use other libraries (e.g. nanovg) that include these dependencies.
While I could not define the `STB_IMAGE_IMPLEMENTATION` macro, it seems if the system version is different from the version included with tinygltf, I could get conflicts or subtle bugs.

I can edit your code to include e.g. from the system path `#include <stb/stb_image_write.h>` or `<nlohmann/json.hpp>` as a workaround.

**To Reproduce**

- OS: any
- Compiler, compiler version, compile options: any

**Expected behaviour**

I can specify to use system STB and JSON headers. Other workarounds would also be ok, e.g., forcing users to download/install third-party code themselves.

**Screenshots**
na

**Additional context**
na

**Comment by syoyo** [comment]
TinyGLTF is a single header-only library, so recommended way is simply copy `tiny_gltf.h` to your repository.
stb_image and json libraries are provided to compile test an example programs.

You can use `TINYGLTF_NO_INCLUDE_STB_IMAGE` and include your own stb_image.h outside of `tiny_gltf.h` include in your app(NO_INCLUDE macro are also provided for JSON library):  https://github.com/syoyo/tinygltf#compile-options

**Comment by dyollb** [comment]
ok, thanks for the prompt answer!
