### ISSUE TITLE
MinGW don't have an implementation of the function "_wfopen_s"

### ISSUE THREAD

**Issue by RE-Kovalev** [syoyo/tinygltf#434]
**Describe the issue**

MinGW x32 for Windows don't have an implementation of the function "_wfopen_s" and "errno_t" is undefined. This issue is found in tiny_gltf.h:2838: "bool FileExists(const std::string &abs_filename, void *)". 

**To Reproduce**

- Windows 10
- gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0 (x32)

**Possible solutions**
Possible solutions is replace "_wfopen_s" and "errno_t" with something like "FILE *fp = _wfopen(...":
tiny_gltf.h:2853:
```
#ifdef _WIN32
#if defined(_MSC_VER) || defined(__GLIBCXX__) || defined(_LIBCPP_VERSION)

  // First check if a file is a directory.
  DWORD result = GetFileAttributesW(UTF8ToWchar(abs_filename).c_str());
  if (result == INVALID_FILE_ATTRIBUTES) {
    return false;
  }
  if (result & FILE_ATTRIBUTE_DIRECTORY) {
    return false;
  }

  FILE *fp = _wfopen(UTF8ToWchar(abs_filename).c_str(), L"rb");
  if (fp == nullptr) {
    return false;
  }
```

**Compiler output**
```
In file included from C:\ogl\19/src/Model.cpp:554:0:
c:\ogl\dependencies\tinygltf\tiny_gltf.h: In function 'bool tinygltf::FileExists(const string&, void*)':
c:\ogl\dependencies\tinygltf\tiny_gltf.h:2866:3: error: 'errno_t' was not declared in this scope
   errno_t err = _wfopen_s(&fp, UTF8ToWchar(abs_filename).c_str(), L"rb");
   ^~~~~~~
c:\ogl\dependencies\tinygltf\tiny_gltf.h:2866:68: error: '_wfopen_s' was not declared in this scope
   errno_t err = _wfopen_s(&fp, UTF8ToWchar(abs_filename).c_str(), L"rb");
                                                                        ^
```

**Comment by syoyo** [comment]
Oh good find! `FileExists` function is added recently and it has no consideration for MinGW.

Implementing MinGW code path when `__GLIBCXX__` is defined like this:

https://github.com/syoyo/tinygltf/blob/7a570c88d996918489bbbd3af7ebbda1f3f74a0a/tiny_gltf.h#L2997

should solve the issue. PR is much appreciated!

**Comment by RE-Kovalev** [comment]
Thanks!

**Comment by RE-Kovalev** [comment]
Excuse me. It's still falls in that issue.
Problem in the 2853 line:
```
#ifdef _WIN32
#if defined(_MSC_VER) || defined(__GLIBCXX__) || defined(_LIBCPP_VERSION)
```
I suggest:
```
#ifdef _WIN32
#if defined(_MSC_VER) || defined(_LIBCPP_VERSION)

  // First check if a file is a directory.
  DWORD result = GetFileAttributesW(UTF8ToWchar(abs_filename).c_str());
  if (result == INVALID_FILE_ATTRIBUTES) {
    return false;
  }
  if (result & FILE_ATTRIBUTE_DIRECTORY) {
    return false;
  }

  FILE *fp = nullptr;
  errno_t err = _wfopen_s(&fp, UTF8ToWchar(abs_filename).c_str(), L"rb");
  if (err != 0) {
    return false;
  }
#elif defined(__GLIBCXX__)
  FILE *fp = fopen(abs_filename.c_str(), "rb");
  if (!fp) {
    return false;
  }
#else
  // TODO: is_directory check
  FILE *fp = nullptr;
  errno_t err = fopen_s(&fp, abs_filename.c_str(), "rb");
  if (err != 0) {
    return false;
  }
#endif
```

**Comment by RE-Kovalev** [comment]
I made pull-request for this fix.

**Comment by syoyo** [comment]
Thanks! PR #435 merged. This issue should be ready to close.

**Comment by 9hsein5** [comment]
`#ifdef _WIN32
#if defined(__GLIBCXX__)  // mingw
  int file_descriptor =
      _wopen(UTF8ToWchar(filepath).c_str(), _O_RDONLY | _O_BINARY);
  __gnu_cxx::stdio_filebuf<char> wfile_buf(file_descriptor, std::ios_base::in);
  std::istream f(&wfile_buf);`  I am getting again the error mingw
