### ISSUE TITLE
SerializeValue Bug

### ISSUE THREAD

**Issue by lyLoveSharon** [syoyo/tinygltf#44]
https://github.com/syoyo/tinygltf/blob/1e94d0501276fda112d5d987ecc9d994ff0c2adb/tiny_gltf.h#L3282

std::vector<std::string> valueKeys;
should be
std::vector<std::string> valueKeys = value.Keys();

**Comment by syoyo** [comment]
Oops, thank you for finding an issue.

Now fixed!
