### ISSUE TITLE
LoadBinaryFromMemory fails for empty but not omitted binary chunk

### ISSUE THREAD

**Issue by EricGriffith** [syoyo/tinygltf#440]
**Describe the issue**

LoadBinaryFromMemory requires that the binary chunk be either omitted entirely OR be at least 12 bytes in size (8 for header + 1 to 4 bytes of data). However, the spec only says that it SHOULD be omitted if it is empty, not that it MUST be omitted. Based on this, it seems like it should be valid for the binary chunk to be 8 bytes in length with the chunk length set to 0.

**To Reproduce**

Parse a glTF that has a binary chunk with 0 length that is NOT omitted.

**Expected behaviour**

The glTF is parsed successfully.

**Additional context**
Relevant line is 6643:
`if ((header_and_json_size + 12ull) > uint64_t(length)) {`

**Comment by syoyo** [comment]
Could you please attach reproducible glb file?(or point a such file in https://github.com/KhronosGroup/glTF-Sample-Models)

**Comment by syoyo** [comment]
According to the spec,

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#binary-buffer

> When the binary buffer is empty or when it is stored by other means, this chunk SHOULD be omitted.

SHOULD means `RECOMMENDED`, so 

> the binary chunk to be 8 bytes in length with the chunk length set to 0.

8byte bin chunk(chunk length 0) must be a valid glb file.
