### ISSUE TITLE
Version numbers in header file is outdate

### ISSUE THREAD

**Issue by Demonese** [syoyo/tinygltf#441]
https://github.com/syoyo/tinygltf/blob/f51243da480806032cfb6f8d6799a7493397cb86/tiny_gltf.h#L28

Other issues: The missing patch version number
![image](https://github.com/syoyo/tinygltf/assets/57629614/4f7be394-24ff-4ad2-bc1c-6ef5e573ced8)

**Comment by syoyo** [comment]
Good find, fixed: https://github.com/syoyo/tinygltf/releases/tag/v2.8.14

I'm considering to remove version number in .h file
