### ISSUE TITLE
Generic extension support

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#46]
Hi,

Currently, if I want to develop and use a custom extension, I would have to add parsing of this extension to the code.

Instead, would it not be more convenient to put every ParameterMap inside... well.. another map, indexing by string?

Something like this:

```
typedef std::map<std::string, ParameterMap> ExtensionMap;

ParseExtensions(...)

struct Material {
  ...
  ExtensionMap extensions;
  ...
}

... {
  if (it.key() == "extensions")
  {
    ExtensionMap extensions;
    if(ParseExtensions(...)) {
      material->extensions = extensions;
    }
  }
}
```

**Comment by Selmar** [comment]
Of course, I will do this and submit a pull request if we can agree on something. :)

**Comment by syoyo** [comment]
Yeah! No one is working on extension. PR appreciated!

**Comment by Selmar** [comment]
Alright. What should we do about the existing extension structures that exist in various places?
```
struct Material {
  ...
  ParameterMap extCommonValues;   // KHR_common_material extension
  ParameterMap extPBRValues;
}
```
I suppose we should just remove them?

**Comment by Selmar** [comment]
For example, the `KHR_lights_cmn` extension can be accessed afterwards by simply using

`node->extensions["KHR_lights_cmn"]` instead of `node->extLightsValues`

Perhaps we could add some macros for the extension names for convenience, or do you think that's out of scope?

**Comment by Selmar** [comment]
Perhaps there is an issue with using the ParameterMap, as there might be several levels of nesting inside an extension value. It's still better than what currently exists, though.

**Comment by Selmar** [comment]
Could whoever added the lights chime in on how you want to deal with re-serializing them?

The `model->lights` property, which comes from an extension, is actually written back as if it was a part of the spec (e.g. outside of the extensions or extras objects).

If we just serialize the extensions array as-is, the data will be in the glTF twice, so we'd have to exclude that specific extension on serialization. However, this may cause other glTF users to not be able to load this extension data.

To me, it seems like the "correct" way is to leave it inside the extensions property.

**Comment by syoyo** [comment]
`KHR_common_material` and  other some hard-coded extension are tentative implementation. If we have generic extension support, we could remove it. For a while, you can create a new branch for generic extension support without considering serialization and existing hard-coded extension support, then I'll consider how to merge it.

**Comment by Selmar** [comment]
At this point I have already completed the serialization part as well. The only `problem` is now that the data is in there twice.

I will create a pull request shortly and you can see what to do about it.

**Comment by syoyo** [comment]
> At this point I have already completed the serialization part as well. The only problem is now that the data is in there twice.

I see.

> I will create a pull request shortly and you can see what to do about it.

Thanks!

**Comment by Selmar** [comment]
Merged, so closing.

**Comment by syoyo** [comment]
Thanks!
