### ISSUE TITLE
SerializeNumberProperty always serializes to double

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#47]
It takes a template parameter, but doesn't use it. Mistake?

**Comment by syoyo** [comment]
@AurL may have comments on this.

**Comment by Selmar** [comment]
There is actually a bug with this when you try to reload from the serialized file, because when parsing the `scene` property the code checks whether the number is an integer (which it is not, now, in fact).

The spec also distinguishes between `integer` and `number` types, so this loading behaviour is, strictly speaking, correct.

**Comment by syoyo** [comment]
> The spec also distinguishes between integer and number types, so this loading behaviour is, strictly speaking, correct.

JSON itself does not distinguish integer and double for `number` variable, so casting value to `double` would be OK.

But we could use the following change if this does not produce side effects. How do you think @AurL ?

```
template <typename T>
static void SerializeNumberProperty(const std::string &key, T number,
                                    json &obj) {
  obj[key] = number;
}
```

**Comment by Selmar** [comment]
It is not a concern for us, I just noticed there was a problem.

I guess this could be changed? 

`if ((rootIt != v.end()) && rootIt.value().is_number_integer())`
to
`if ((rootIt != v.end()) && rootIt.value().is_number())`

**Comment by syoyo** [comment]
> I just noticed there was a problem.

Ah, I see. Fixed with your suggested solution.
