### ISSUE TITLE
TinyGltf not setting the correct indices when loading a model

### ISSUE THREAD

**Issue by bshafi** [syoyo/tinygltf#472]
**Describe the issue**

I am trying to make a gltf loader and tinygltf is not loading a model. I looked at the tinygltf::Model more closely and found that the indices variable is set to -1. Then I used a glb to gltf converter to inspect my model. The indices variable is set to 0. This model is very simple and it only has 1 mesh and 1 primitive on that mesh.

**To Reproduce**
Load the model with tinygltf's model loader.
- OS: Window
- MSVC
- [The model from gltf samples
](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Fox/glTF-Binary/Fox.glb)
**Expected behaviour**

I expected the model's indices variable to be set to 0. The is only one mesh and one primitive so there is only one indices variable.

**Screenshots**

![image](https://github.com/syoyo/tinygltf/assets/62918721/5223f5c2-b6c7-48f8-906f-82d7b4de2d8f)

The meshes section of the gltf file:
```
"meshes": [
    {
      "primitives": [
        {
          "attributes": {
            "POSITION": 1,
            "TEXCOORD_0": 2
          },
          "indices": 0,
          "material": 0,
          "mode": 4
        }
      ]
    }
  ],
```

**Additional context**
N/A

**Comment by syoyo** [comment]
The model does not have indices, so set to `-1`(undefined)

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-mesh-primitive

```
"meshes":[{"name":"fox1","primitives":[{"attributes":{"POSITION":0,"TEXCOORD_0":1,"JOINTS_0":2,"WEIGHTS_0":3},"material":0}]}]
```

glb to glTF converter is doing a wrong thing.
