### ISSUE TITLE
C2065 'M_PI': undeclared identifier error when building glview.cpp on WIN32

### ISSUE THREAD

**Issue by jam3sward** [syoyo/tinygltf#474]
**Describe the issue**

M_PI is not defined by `<cmath>` on WIN32 unless you first define _USE_MATH_DEFINES
This causes glview.cc to fail to build, but it is easily fixed by defining _USE_MATH_DEFINES prior to including `<cmath>`. This could either be done in the glview.sln or by #define in glview.cc.

**To Reproduce**

- Windows 11
- Visual Studio Professional 2022 version 17.9.1

**Comment by syoyo** [comment]
`M_PI` macro is a problematic thing.

`constexpr double kPI = 3.14159265358979323846` is recommended to use.
PR is much appreciated!

**Comment by jam3sward** [comment]
PR created at #475

**Comment by jamesvert** [comment]
This issue could be closed, as you merged the #475 PR at b132612. Sorry if I confused matters by creating a separate issue number :)

tinygltf is awesome by the way - great job!

**Comment by jam3sward** [comment]
This issue was fixed at https://github.com/syoyo/tinygltf/commit/b13261230707aa0c274e7974c82f7d1b4b11d3fe.

tinygltf is awesome by the way - great job!

**Comment by syoyo** [comment]
Thanks!
