### ISSUE TITLE
WriteGltfSceneToFile (_wopen) might fail when compiling with MinGW (MSYS2)

### ISSUE THREAD

**Issue by The0Dev** [syoyo/tinygltf#477]
**Describe the issue**

The function_wopen might fail to open an existing file created by the previous call to _wopen since the file is created as read-only by default. Passing  _S_IREAD | _S_IWRITE as the third argument solves the issue. 

**To Reproduce**
Call WriteGltfSceneToFile (WriteBinaryGltfFile) twice. 
- OS Windows 10
- Compiler g++ 13.2.0

**Expected behaviour**

Files should be created with the read and write permissions.

**Additional context**

[A related question on Stackoverflow](https://stackoverflow.com/questions/5516011/using-mingw-how-can-i-create-a-file-without-the-read-only-file-attribute)
[Microsoft Learn](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen)

> The pmode argument is required when _O_CREAT is specified

**Comment by syoyo** [comment]
Interesting. Didn't know `_wopen` creates a file as read-only by default.

We'll need to add `_S_IREAD | _S_IWRITE `(or `_S_IWRITE` alone suffices on Windows) to every `_wopen` call where file is open for write.

PR is much appreciated!
