### ISSUE TITLE
Serializing to glTF writes absolute filepath for .bin references

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#48]
This happens when you supply a full file path to save to. I did not try using a relative file path.

**Comment by syoyo** [comment]
What is the expected behavior?

**Comment by Selmar** [comment]
I suppose to create a relative path, like it does with the image uris? 

The spec does not enforce a relative file path:
> The uri of the buffer. Relative paths are relative to the .gltf file. Instead of referencing an external file, the uri can also be a data-uri.

It seems illogical to save an absolute path, though, because it prevents you from sharing or moving the .bin file.

**Comment by syoyo** [comment]
Could you please post a minimal procedure for reproducing issue and expected behavior?

**Comment by Selmar** [comment]
It's just this:

```
std::string error;
tinygltf::Model model;
parser.LoadASCIIFromFile(&model, &error, absoluteFilePath));
parser.WriteGltfSceneToFile(&model, "D:/[someDir]/[someName].gltf");
```

The result is a buffer.uri with an absolute file path, but a different extension. I would expect the buffer.uri property to contain a path relative to the gltf (which is just `gltfFileName.bin` in this case).

**Comment by syoyo** [comment]
Fixed : https://github.com/syoyo/tinygltf/commit/d42767e63f87a2cf32594cd04a92cd8cf14d0601#diff-f70622f14b85ce3409f1f100e5c47ec4R3722

 It should work well on Windows, but if you face an issue, please send us PR.
