### ISSUE TITLE
Loading a GLB file without BIN data fails

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#49]
Forwarding from a colleague. 

In addition to not passing the header size check, accessors, bufferviews and buffers are still flagged as required in the loading process, but in fact are not present in this scenario and should be skipped.

> The GLB file format specification specifies that the Bin header & data of a GLB file are not mandatory (it says the number of BIN headers can be 0 or 1). However, if I try to load a GLB from memory with no Bin buffer, the loader fails.
> This is due to the “LoadBinaryFromMemory” methods that checks the size of the binary data. In case the Bin buffer is not present, the size is exactly 20 + size of JSON contents. The test is done with a greater or equal operator, and so it passes and returns false.
> The suggested fix is to change this operator to a “greater than” operator.
> 
> That is:
> ```
> if ((20 + model_length >= size) || (model_length < 1) ||
>     (model_format != 0x4E4F534A)) {  // 0x4E4F534A = JSON format.
>     if (err) {
>       (*err) = "Invalid glTF binary.";
>     }
>     return false;
>   }
> ```
> Would become:
> ```
>   if ((20 + model_length > size) || (model_length < 1) || // specification allows a GLB file with no bin buffer
>       (model_format != 0x4E4F534A)) {  // 0x4E4F534A = JSON format.
>     if (err) {
>       (*err) = "Invalid glTF binary.";
>     }
>     return false;
>   }
> ```

**Comment by syoyo** [comment]
Good catch! Fixed with suggested solution.

**Comment by Selmar** [comment]
I believe it should also set the accessors, buffers and bufferviews to not be required? They will not be present without BIN data.
