### ISSUE TITLE
WriteImageData not called

### ISSUE THREAD

**Issue by ptc-tgamper** [syoyo/tinygltf#495]
**Describe the issue**

Our use requires not to load images into memory at all, since there might Gigabytes of them. The most promising attempt at implementing this seems to be to use a custom ImageLoaderFunction and a custom ImageWriterFunction. The custom image loader simply does nothing, leaving the images empty. But writing the glTF model after loading does not work then, the images are completely omitted.

**To Reproduce**

- macOS Sonoma
- Xcode 15.3

```
bool LoadImageData(tinygltf::Image *, const int,
                   std::string *, std::string *, int, int,
                   const unsigned char *, int, void *) {
    return true;
}

bool WriteImageData(const std::string *, const std::string *,
                    const tinygltf::Image *, bool,
                    const tinygltf::FsCallbacks*, const tinygltf::URICallbacks *,
                    std::string *, void * ptr){
    REQUIRE(ptr != nullptr);
    auto counter = static_cast<int*>(ptr);
    *counter = *counter + 1;
    return true;
    
}

TEST_CASE("empty-images-not-written") {

    std::string err;
    std::string warn;
    tinygltf::Model model;
    tinygltf::TinyGLTF ctx;
    ctx.SetImageLoader(LoadImageData, nullptr);
    bool ok = ctx.LoadASCIIFromFile(&model, &err, &warn, "../models/Cube/Cube.gltf");
    REQUIRE(ok);
    REQUIRE(err.empty());
    REQUIRE(warn.empty());

    REQUIRE(model.images.size() == 2);
    REQUIRE(model.images[0].uri == "Cube_BaseColor.png");
    REQUIRE(model.images[1].uri == "Cube_MetallicRoughness.png");
    REQUIRE(model.images[0].image.empty());
    REQUIRE(model.images[1].image.empty());

    int counter = 0;
    ctx.SetImageWriter(WriteImageData, &counter);
    ok = ctx.WriteGltfSceneToFile(&model, "Cube.gltf");
    CHECK(ok);
    CHECK(counter == 2);

}
```

**Expected behaviour**

It should be possible to save the images to disk in the target directory. That does not happen because WriteImageData() is not invoked for images without actual image data, even though the image has a valid URI.
Moreover, images encoded as data URIs are lost, too, because their URI is discarded during parsing, but outside of the LoadImageData() function.

**Screenshots**

**Additional context**

**Comment by syoyo** [comment]
WriteImageData is only called when both filename and image data are filled.

https://github.com/syoyo/tinygltf/blob/fea67861296293e33e6caee81682261a2700136a/tiny_gltf.h#L3316

Probably we may better allow calling WriteImageData callback always(when WriteImageData callback is set)?

**Comment by ptc-tgamper** [comment]
I have a fix, will create PR soon.
