### ISSUE TITLE
glTF images with data URI lose their URI during parsing

### ISSUE THREAD

**Issue by ptc-tgamper** [syoyo/tinygltf#497]
**Describe the issue**

During parsing  of glTF Images that store their data in a data URI, the latter is discarded. Only images that reference an external file keep their URI, see https://github.com/syoyo/tinygltf/blob/10b23b6af22c8692434690a06ffe84e3fc12f561/tiny_gltf.h#L4398
Therefore, when one uses a custom image loader that leaves `image.image` empty, the image data cannot be loaded later from the original data URI.

**To Reproduce**

- OS
- Compiler, compiler version, compile options
- Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data

**Expected behaviour**

The image's URI should not be discarded if it is not loaded into `image.image`

**Screenshots**

**Additional context**
We are using a custom image loaderto avoid loading images into memory, since our models have Gigabytes of images. Naturally then the custom image writer needs to have access to the original image data. But the original image.uri has been lost during parsing.

**Comment by syoyo** [comment]
You should describe the issue in clear manner. Also should attach minimal reproducible code&gltf file.

**Comment by ptc-tgamper** [comment]
https://github.com/syoyo/tinygltf/pull/498 has a respective test case. It generates a glTF file that shows the problem on the fly.
