### ISSUE TITLE
glTF model forgets its own base directory

### ISSUE THREAD

**Issue by ptc-tgamper** [syoyo/tinygltf#499]
**Describe the issue**

We employ a custom image loader, that loads no image data. We also employ a custom image writer, which then tries to resolve external image references relative to the original base directory. It needs to find the image files there, and then copy them over to the target base directory using the given URI. But the image writer is only passed the target base directory, and the filename to use to save the image there. It does not know where to look for the original files.

**To Reproduce**

- OS
- Compiler, compiler version, compile options
- Please attach minimal and reproducible .glTF file if you got an issue related to .glTF data

**Expected behaviour**

The glTF model should store the base directory it was loaded from. After loading, one is then still able to resolve URIs relative to that base directory.

**Screenshots**

**Additional context**

**Comment by syoyo** [comment]
Model should not have basedir info. Instead, it should be handled in TinyGLTF class.
