### ISSUE TITLE
TODO: Implement serializer

### ISSUE THREAD

**Issue by syoyo** [syoyo/tinygltf#5]
Implement glTF 2.0 serializer(saver)

@AurL, I have refactored `devel` branch and now `devel` branch will be ready to accept serializer PR from you. Could you please send your serializer PR to `devel` branch?

**Comment by AurL** [comment]
@syoyo Thanks! Will do
I have to finish some stuff on my side before going back to tinygltf and making the PR, I hope it's ok for you
I'll let you know! (should be this week)

**Comment by syoyo** [comment]
Thanks!

BTW do you know any good PBR GLSL shader for `examples/glview`, @AurL ?

**Comment by AurL** [comment]
Hum, I guess you can use the code from the [osgjs PBR example](https://github.com/cedricpinson/osgjs/tree/master/examples/pbr/shaders)
Note that a pre-computed enviroment is required, you should be able to use [the data here](https://github.com/cedricpinson/osgjs/tree/master/examples/pbr)

**Comment by syoyo** [comment]
Thanks! I will look into these > osgjs, laugh_engine.

laugh_engine looks great!

**Comment by AurL** [comment]
Hi @syoyo, 

I pushed a PR (not finished) with serialization functions. Could you take a quick look ?
Also, tests are fine locally but they fail on the PR, did I miss something ?

Thanks!

**Comment by syoyo** [comment]
Thanks! I will look into your PR!

**Comment by syoyo** [comment]
PR merged into `devel` and doing some code refactoring. After adding some serialization example code, I'm planning to merge `devel` into `master` and this become an initial TinyGLTF release!

**Comment by AurL** [comment]
Hi @syoyo,

Just to let you know that I updated tinygltf again and we are now using it in our export pipeline to generate glTF 2.0 files that are validator compliant. (There might be some warnings, and a few unhandled edge cases).

I saw that you made some updates, what's the easiest way to submit mine ? Did you made some test on the previous code and spot some issues/points that need to be improved ?

**Comment by syoyo** [comment]
Cool! 

I have fixed some issues and added serialization for Camera in recent `devel` branch.

It would be nice if you create a PR against recent `devel` branch.

Unfortunately, I haven't wrote enough tests on serializer yet...

**Comment by syoyo** [comment]
`devel` branch now has initial support of serializer.
