### ISSUE TITLE
Buffer.uri not set after loading buffer

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#50]
This seems inconsistent with loading images. In addition, we actually need the uri for caching purposes.

Is there a specific reason for this, or can we perhaps save it? : )

**Comment by syoyo** [comment]
We may store add original url to `Buffer.orignal_url`  if required.
(Not sure its ok to save url to `Buffer.url`)

> we actually need the uri for caching purposes.

How about to use `Buffer.name` for caching?

**Comment by Selmar** [comment]
We require the file to get the timestamp.

Currently the `buffer.uri` property is not referenced anywhere.

Adding `original_uri` is fine, too, of course.

**Comment by syoyo** [comment]
Ah, it should be simply my mistake not saving uri.

Now fixed here: https://github.com/syoyo/tinygltf/commit/20244e1e4e8938b2e51d109a4bc2f57946e5ee5d#diff-f70622f14b85ce3409f1f100e5c47ec4R1789
