### ISSUE TITLE
Texcoords are incorrect upon loading with TinyGLTF

### ISSUE THREAD

**Issue by sstarbright** [syoyo/tinygltf#502]
**Describe the issue**

Texture Coordinates seem to be incorrect. The model in question was exported from Blender, but when I import the mesh into my engine using this library, the Texture coordinates are broken. Here is the code I'm using to load the data:
```
if (meshData->attributes.find("TEXCOORD_0") != meshData->attributes.end()) {
        tinygltf::Accessor uvAccessor = model->accessors[meshData->attributes["TEXCOORD_0"]];
        tinygltf::BufferView uvView = model->bufferViews[uvAccessor.bufferView];
        unsigned int uvSize = uvAccessor.ByteStride(uvView);
        for (unsigned int i = 0; i < uvAccessor.count; i++) {
            unsigned char* uvData = (unsigned char*)&vertices[i].TexCoords0;
            unsigned int uvOffset = uvAccessor.byteOffset+uvSize*i;

            for (unsigned int k = 0; k < uvSize; k++) {
                uvData[k] = meshBuffer.data[uvOffset+k];
            }
        }
    }
```
 I just copy the bytes into a TexCoords0, a glm::vec2 within my Vertex struct. This method works perfectly fine for COLOR_0, but TEXCOORD_0 seems to not work correctly. Is there anything I'm doing wrong here? Should I be adjusting the coordinate data in any way after I load it?

**To Reproduce**

- OS: Any
- Compiler, compiler version, compile options: Any
- [GLTF File to reproduce](https://drive.google.com/file/d/1-1q_-DxHlOzbAGdERwJETcGk-Rz3NViu/view?usp=sharing)

**Expected behaviour**

I expected the textures to be displaying as they do in Blender, as well as the GLTF Viewer I use for VSCode. 

**Screenshots**

### In Blender
![overworld_blender](https://github.com/user-attachments/assets/267979b9-951d-4748-a3b4-ddd93e55b29f)

### In a VSCode GLTF Viewer
![image](https://github.com/user-attachments/assets/95add8cb-3500-45dd-9566-28ee9df1a17d)
### In Engine
![overworld_engine](https://github.com/user-attachments/assets/2214b727-36e9-439f-9b80-d7f245256cb4)

**Comment by syoyo** [comment]
You should not post unreproducible issue
