### ISSUE TITLE
Current Master Requires Copying Header to Source if Using as a Cmake Submodule

### ISSUE THREAD

**Issue by thearchivalone** [syoyo/tinygltf#506]
**Describe the issue**

Not much else to add; the title hopefully was concise enough.

**To Reproduce**

- Windows 11
- Clang 19.3.1,  default compiler flags (minus running as C++ STD 20 for another library that required it)

1) Clone latest master as a submodule for another project
2) Set to Header Only and disable install
3) Disable building of the loader example (since that's not needed but still was being built otherwise as a submodule)
4) Implement header and definitions in a single cc file

**Expected behaviour**

Followed the guide on how to use as a CMake submodule and expected the header to be included on my search path but still needed to copy tiny_gltf.h to my main include directory for it to be used.

**Additional context**
Adding a cc file with just the implementation requirements didn't affect it due to the header not being found in the original issue.

**Comment by thearchivalone** [comment]
One way to solve this for anyone else that is running into it:

Add this to your top level CMakeLists.txt file: `target_include_directories(${PROJECT_NAME} PRIVATE "thirdparty/tinygltf"`

NOTE: your path will be different than mine but `${PROJECT_NAME}` is a standard CMAKE variable. If this is being built as part of a library that is used in a project, you can use the library name instead.

**Comment by syoyo** [comment]
`target_include_directories` will be the solution. If you found more better solution, please send a fix via PR.

**Comment by thearchivalone** [comment]
That's honestly the most straightforward one. There may be a way to automate it with variables but adding that to the documentation might be best. Normally, when you're able to embed a library as a subdirectory, there's a mechanism that automates it. Since this is not a complex library, I don't see going through the effort of getting that working being as necessary.

Closing since you answered and agreed with my original solution.

**Comment by syoyo** [comment]
>  adding that to the documentation might be best. 

PR(Describe  `target_include_directories` to README)  is much appreciated!
