### ISSUE TITLE
compile error C2100

### ISSUE THREAD

**Issue by helen00** [syoyo/tinygltf#65]
![image](https://user-images.githubusercontent.com/28391325/38618325-dc78dda2-3dcb-11e8-8490-be28f2ad44b7.png)

**Comment by syoyo** [comment]
Please read README carefully.

```
Windows + Visual Studio 2015 or later.
Visual Studio 2013 is not supported since they have limited C++11 support and failed to compile json.hpp.
```

**Comment by helen00** [comment]
I use windows 10 and  Visual Studio 2015
