### ISSUE TITLE
window10+vs2015 compile error

### ISSUE THREAD

**Issue by helen00** [syoyo/tinygltf#66]
![image](https://user-images.githubusercontent.com/28391325/38651918-3dd3f176-3e36-11e8-88e6-f8e4a15bd17b.png)

**Comment by helen00** [comment]
got it~ need VS2015 Update 3 for 2.1.1 to work.

**Comment by syoyo** [comment]
Good! Added `Update 3` to README > https://github.com/syoyo/tinygltf/commit/c89fc5f06b750e2309a53075ac90fcf238e0d3b3
