### ISSUE TITLE
typdef Buffer in the header makes forward declaration fail.

### ISSUE THREAD

**Issue by PsycoTodd** [syoyo/tinygltf#67]
I notice that some type like Buffer is a typedef in h. This makes forward declearation in other header files not possible (https://stackoverflow.com/questions/18501993/struct-forward-declaration-error-typedef-redefinition-with-different-types).

Is that a special feature in tiny_gltf to avoid user directly define functions to use these types? Or should we just makes all typedef to struct?

Thank you.

**Comment by syoyo** [comment]
I see. Simply I was just lazy for definitions.

Now its good time to make definitions well-organized(i.e. use `struct Buffer`)

**Comment by PsycoTodd** [comment]
No problem just to double check. On my side I can always use gltfModel as parameter and by pass the forward declaration of buffer for now.

**Comment by syoyo** [comment]
Rewrite struct definition in this commit: https://github.com/syoyo/tinygltf/commit/2d17a31d3bf507c1005af5cd26f39bde79f2dad3

I think this should fit to your usage.
