### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ladiszlai** [syoyo/tinygltf#68]
I tried to load a model with your example but the visual gave me this compile errors for TinyGLTF class declaration:

`everity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl tinygltf::LoadImageData(struct tinygltf::Image *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *,int,int,unsigned char const *,int,void *)" (?LoadImageData@tinygltf@@YA_NPAUImage@1@PAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HHPBEHPAX@Z) referenced in function "public: __thiscall tinygltf::TinyGLTF::TinyGLTF(void)" (??0TinyGLTF@tinygltf@@QAE@XZ)`

and

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl tinygltf::WriteImageData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,struct tinygltf::Image *,bool,void *)" (?WriteImageData@tinygltf@@YA_NPBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0PAUImage@1@_NPAX@Z) referenced in function "public: __thiscall tinygltf::TinyGLTF::TinyGLTF(void)" (??0TinyGLTF@tinygltf@@QAE@XZ)`

I am using MSV 2015

**Comment by bowald** [comment]
Both **LoadimageData** and **WriteImageData** function uses stb_image.h and stb_image_write.h
Make sure that you have defined **STB_IMAGE_IMPLEMENTATION**, **STB_IMAGE_WRITE_IMPLEMENTATION**, where the **TINYGLTF_IMPLEMENTATION** is defined. Otherwise you will get unresolved external symbols errors in those functions.

```
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
```

Also when on windows define **STBI_MSC_SECURE_CRT** to avoid warnings from stb_image_write.h
```
#define STBI_MSC_SECURE_CRT
```

Hope this helps you. 😃

**Comment by ladiszlai** [comment]
It didn't worked :/

**Comment by ladiszlai** [comment]
Yeah I think this is the problem because I don't have updates on MSV 15. How can I update to 3 if I don't want to install 2017 ? (I have no more storage and there are unfinished projects for 15)

**Comment by ladiszlai** [comment]
Okay I found out that I already have Update 3. So now I have no idea why this is crashing for me.
Here is my full code:

`#include <iostream>
#include <string>
#include <fstream>
#include <vector>

#include "Converter.h"
#include "tiny_gltf.h"

#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_MSC_SECURE_CRT

using namespace std;
using namespace tinygltf;


int main(int argc, char **argv)
{
	Model model;
	TinyGLTF loader;
	std::string err;

	bool ret = loader.LoadASCIIFromFile(&model, &err, argv[1]);
	//bool ret = loader.LoadBinaryFromFile(&model, &err, argv[1]); // for binary glTF(.glb) 
	if (!err.empty())
		cout << "Err: %s\n";
	

	if (!ret) 
	{
		cout << "Failed to parse glTF\n";
		return -1;
	}




	cin.get();
    return 0;
}`

**Comment by syoyo** [comment]
You should define

```
#define TINYGLTF_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STBI_MSC_SECURE_CRT
```

Before including `tiny_gltf.h`

**Comment by xackery** [comment]
> You should define
> 
> ```
> #define TINYGLTF_IMPLEMENTATION
> #define STB_IMAGE_IMPLEMENTATION
> #define STB_IMAGE_WRITE_IMPLEMENTATION
> #define STBI_MSC_SECURE_CRT
> ```
> 
> Before including `tiny_gltf.h`

This just helped me out, thanks for the tip!
