### ISSUE TITLE
String tags in original gltf outputs as empty string ""

### ISSUE THREAD

**Issue by h3r** [syoyo/tinygltf#70]
I'm trying to integrate tinygltf in my framework. A simple way to manage all the resources loaded is storing them in a map container using strings. On any string tag like material name, mesh name, texture name etc i am always getting empty string "".

**Comment by syoyo** [comment]
Please post minimal & reproducable code of your problem.

**Comment by Ybalrid** [comment]
As far as I can tell, if the strings like the objects or material names are defined in the original gltf/glb files, they come out fine from the tinygltf API. So... Seems like a non-issue?
e.g. `model.materials[X].name` contains the name of the requested material...
