### ISSUE TITLE
Current index of array elements

### ISSUE THREAD

**Issue by sjfricke** [syoyo/tinygltf#72]
Unless there is a better parsing method idk about, it seems very useful to have the ability to self-identify which index an item is. For example, if I pass in a `tinygltf::Node` to a function I am finding myself also passing its index as a 2nd parameter. I also will pass in the top `tinygltf::Model` but then I need to transverse the entire list of Nodes to check if its the same if I am trying to match an animation sampler up to it.

Not sure if this is outside scope of tinygltf, but seems like the simplest fix for an issue I keep reincurring.

**Comment by syoyo** [comment]
I see. It may be better to have mapping of ID <-> Node(or other glTF object) in somewhere and provide `Find` method for looking up glTF object by ID(or vice versa).

If you already have an traversal code, embed it to `TinyGLTF` class, then PR appreciated so that we can review&merge it.
