### ISSUE TITLE
Images and buffers with a space in the filename will not load in Linux build of tinygltf

### ISSUE THREAD

**Issue by bowald** [syoyo/tinygltf#74]
Gltf models with separate images and buffers, with a space in the filename will not load.
The bug only occurs in Linux build, (it can not be reproduced on windows.)

How to reproduce:
* use an gltf model where either a texture of buffer is stored as a separate file with a name containing a space.
* Load the model

I have attached a model, [duck with spaces.zip](https://github.com/syoyo/tinygltf/files/2067311/duck.with.spaces.zip), that fails when loaded by loader_example.

**Comment by bowald** [comment]
I will try to fix this when I have time in the coming weeks. However, if anyone wants to fix this before I do, feel free to do it :)

**Comment by syoyo** [comment]
The reason would be `wordexp()` in `ExpandFilePath()`. `wordexp()` is used to expand `~` and some environment variables, but it looks it cannot work well when file path contains spaces.

**Comment by bowald** [comment]
I see

If we wrap the filepath in quotes, wordexp works with spaces

potential fix in `ExpandFilePath()` would be:
```
  std::string temp = "\"" + filepath + "\"";
  int ret = wordexp(temp.c_str(), &p, 0);
```

**Comment by syoyo** [comment]
> If we wrap the filepath in quotes, wordexp works with spaces

Thanks! I have confirmed concatinating `we_wordv` work also, but this may be affected by `$IFS` environment variables according to man page: https://linux.die.net/man/3/wordexp , so wrapping the filepath should be better answer.

**Comment by syoyo** [comment]
Fixed! Thanks!
