### ISSUE TITLE
Make overriding FileExists, LoadExternalFile, ExpandFilePath, ... possible

### ISSUE THREAD

**Issue by UberLambda** [syoyo/tinygltf#77]
tinygltf currently assumes that external files physically reside on the host's filesystem. In many game engines and similiar programs, however, files are packed in virtual "container" files and/or managed by libraries such as [PhysicsFS](https://icculus.org/physfs/) that do not directly access the physical filesystem.

A simple way to solve this issue would be making the prototypes of`FileExists`, `LoadExternalFile`, `ExpandFilePath` and any other file I/O functions be visible to the user and letting their default implementations be disabled by `#define TINYGLTF_NO_FS_IMPLEMENTATION`.

I could try implementing this functionality and pushing it to the repo if you would like.

**Comment by Ybalrid** [comment]
This is much appreciated. I'm currently working on a project using tinygltf where the final goal would be to load the data through the `ResourceGroupManager` of the 3D graphics library `Ogre`. 

To achieve this, being able to define these I/O operation in the user code, and not use the standard file I/O is needed.

**Comment by UberLambda** [comment]
As of 81bbf86 required changes should be in devel, closing :+1:
