### ISSUE TITLE
Data URI buffers in binary files not read

### ISSUE THREAD

**Issue by clintbrewer** [syoyo/tinygltf#79]
ran into this likely rare case, where a data uri  was used for a buffer inside of a glb file.     the parser skipped over it. 

suggested change,  inside of ParseBuffer right after the !uri.empty()  check,
make sure to try to parse a datauri first, 
see below.
snip---------------------------------------
 if (is_binary) {
    // Still binary glTF accepts external dataURI. First try external resources.

    if (!uri.empty()) {
        if (IsDataURI(uri)) {   // <--- Here
            if (!DecodeDataURI(&buffer->data, uri, bytes, true)) {
                if (err) {
                    (*err) += "Failed to decode 'uri' : " + uri + " in Buffer\n";
                }
                return false;
            }
        }
        else {
            // Assume external .bin file.
            LoadExternalFile(&buffer->data, err, uri, basedir, bytes, true);
        }		
    } else {
      // load data from (embedded) binary data
snip--------------------------------------------

**Comment by syoyo** [comment]
> where a data uri was used for a buffer inside of a glb file

I see.  @clintbrewer Do you have (minimal) reproducable .glb file for it?

**Comment by clintbrewer** [comment]
yes, please find attached
[box01.zip](https://github.com/syoyo/tinygltf/files/2181016/box01.zip)

**Comment by syoyo** [comment]
Thanks! I have fixed an issue and added box01.glb to regression tests. Please double check the recent `devel` fixes an issue.
