### ISSUE TITLE
memory leak using LoadASCIIFromString

### ISSUE THREAD

**Issue by PandaTeemo** [syoyo/tinygltf#84]
loading a simple cube GLTF with embedded mesh data (no additional files) leaks 2 allocations. works fine with GLB equivalent.

i detected this using a custom memory allocator which asserts if every alloc isnt freed on exit.

tested with vs2015

**Comment by syoyo** [comment]
Please submit minimal and reproducable data&code.
 
I can't see any memory leaks by using ASAN when loading `modesl/Cube/Cube.gltf` with  `loader_example` program.

**Comment by PandaTeemo** [comment]
main cpp + sample model attached. output is. 

**before: 0
status: 1
after:  2**

should be

**before: 0
status: 1
after:  0**

[memleak.zip](https://github.com/syoyo/tinygltf/files/2284957/memleak.zip)

**Comment by syoyo** [comment]
I got

```
before: 1
status: 1
after: 1
```

on Linux.

**Comment by PandaTeemo** [comment]
Problem is on windows in visual studio 2015.

I tried in linux and got your results.

**Comment by PandaTeemo** [comment]
Hi I think i found problem on my end caused by an old library. Sorry for
trouble :)
