### ISSUE TITLE
devel & master Branches way out of sync?

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#87]
I just noticed this when looking at the branch tree, `master` was recently (June 4th) modified with some fixes, but it was last changed a very long time before that. Was this a mistake?

**Comment by syoyo** [comment]
`devel` was default branch(mainstream) for a long time.
That might be a mistake > `master` was recently (June 4th) modified with some fixes

`devel` is not getting mature and stable so I have merged `devel` into `master` and set `master` as default branch.

Please use `master` branch from now on.
