### ISSUE TITLE
bufferView byteStride is read into the byteLength field

### ISSUE THREAD

**Issue by brycehutchings** [syoyo/tinygltf#9]
Offending line of code: `ParseNumberProperty(&byteLength, err, o, "byteStride", false);`

Since many glTF files exclude this property, many files will load fine. One example asset I found which will cause this issue is "GearboxAssy.glb" from glTF-Sample-Models.

**Comment by syoyo** [comment]
Thanks for reporting the issue! Now fixed in `devel` branch! https://github.com/syoyo/tinygltf/commit/a12620f3784954e910f74555af6bc6cfbdf543cc

**Comment by brycehutchings** [comment]
Great, thanks! I also noticed the `Accessor` type has a `byteStride` field which is not in the 2.0 spec. I'm guessing this is a leftover from the 1.0 spec/implementation.

**Comment by syoyo** [comment]
> I also noticed the Accessor type has a byteStride field which is not in the 2.0 spec

Thanks! Fixed > https://github.com/syoyo/tinygltf/commit/822788921e0a03755e028a569b468ad8add2a272
