### ISSUE TITLE
Validation for serialization

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#94]
Hi,

I'm wondering if there is currently any way to validate that serialization is working correctly? The project I'm working on has many and rather large models, so any mismatch is a potentially large time-waster. There have been a few errors before (as I've seen and submitted pull requests to fix them), so this could help in both catching mistakes and testing new implementations. 

E.g. I would like to compare model data using the equals `==` operator. If it is a wanted feature, I could make a pull request.

Alternatively, I imagine the json parser implements the equals operator, so perhaps we could refactor to make use of that?

Any ideas and concerns are welcome.

**Comment by syoyo** [comment]
There is a validator example using json-schema-validator https://github.com/syoyo/tinygltf/tree/master/examples/validator , so you can run it as a postprocess after serialization or in an unit tester.
(Or you could use python script if you don't need to stick with C++11) 

> Alternatively, I imagine the json parser implements the equals operator, so perhaps we could refactor to make use of that?

Do you mean you'd like to compare input  glTF and glTF schema with `==` operator?

It could be possible and rather easy, but in such a case we need to include/prepare glTF schema files in some way(stringify and embed glTF schema files into .h are one possible solution)

**Comment by Selmar** [comment]
In my case I really want to validate the contents of the files actually, e.g. missing parameters that exist in one but not the other, or mismatching values due to forgetting to serialize something. I'm not too worried about the schema, because if the format is not correct that will either result in a crash or show itself otherwise (e.g. through missing parameters or indeed through any other validation methods we use).

**Comment by syoyo** [comment]
> I already implemented the == operator locally

Good! Is this feature only requires current tinygltf dependency(i.e. json.hpp), if so PR is appreciated.

It would also be nice if we could have out-of-bounds check for integer indices(node, texture, target, etc) which cannot be validated using JSON schema.

**Comment by Selmar** [comment]
Do you prefer the `operator==()` declaration and/or implementation inside or outside of the class definition?

1.
```
class ClassName
{
  bool operator==(const ClassName& other); // ... declaration
}
// ... implementation
```

2.
```
class ClassName
{
  bool operator==(const ClassName& other)
  {
    // ... implementation with declaration
  }
}
```

3.
```
class ClassName;
bool operator==(const ClassName& one, const ClassName& other); // ... declaration
...
class ClassName
{
}
...
bool operator==(const ClassName& one, const ClassName& other)
{
  // ... implementation
}
```

**Comment by syoyo** [comment]
I think `3` is best since it has less dependency than `1`
We cannot use approach `2` when the amount of implementation of `==` become large.

**Comment by Selmar** [comment]
An advantage of `1` is maybe that you'll be reminded to change the operator== if you change the class?

**Comment by Selmar** [comment]
It all works and now I'm running into missing serialization; e.g. `accessor.name` is not serialized

Is it okay if I fix all serialization issues I encounter and make a combined pull request?

**Comment by Selmar** [comment]
There are a few issues/concerns, not necessarily a problem:

- Looking at the code, loading embedded buffers seems to take up more memory/cpu, which can be significant for large models. The embedded data is completely stored in the `buffer.uri` property and then duplicated in the `buffer.data` property, but for external buffers it's only loaded into `buffer.data` directly.
- Comparing pre-serialization and post-serialization model data will not work for the buffer property and has to be handled separately if the user wants to verify it, because currently the `buffer.uri` property is coded to copy the gltf file name and replace the extension instead of keeping the previous buffer uri.
- Every buffer is saved with the same filename, which should either overwrite the previously written buffer or generate an exception.
- Comparing pre-serialization and post-serialization model data will not work for both buffers or images if they are embedded. This has to be handled separately.

**Comment by Selmar** [comment]
Of course the equality comparison for floats and doubles won't work; I'll have to add specific functions for those using some epsilon. This is okay?

Some of the variables are currently floats, like `PerspectiveCamera::aspectRatio`. Change to double?

**Comment by syoyo** [comment]
> Of course the equality comparison for floats and doubles won't work; I'll have to add specific functions for those using some epsilon. This is okay?

Yes. You may be interested in floating point comparison technique used in Catch2:

https://github.com/catchorg/Catch2/blob/master/docs/assertions.md#floating-point-comparisons

> Some of the variables are currently floats, like PerspectiveCamera::aspectRatio. Change to double?

I think there won't be precision problem for variables in Camera struct, but rewriting it to `double` type is appreciated for keeping consistency with other variables(e.g. Node::rotation)


For other comments, I will evaluate it(pr comment/review it in github PR thread) with given PR.

**Comment by Selmar** [comment]
Closing, as using the equals operator works fine for us.

**Comment by syoyo** [comment]
Thank you for PR!
