### ISSUE TITLE
Empty Value objects & extensions

### ISSUE THREAD

**Issue by Selmar** [syoyo/tinygltf#97]
Hi,

I have some problems with value objects. This is only really a concern when it comes to extensions, because just the definition of an extension may change behaviour, even if the object is empty (e.g. all parameters are default values).

Right now, when reading the gltf file, any empty objects are completely ignored, which results in their type being `TYPE_NULL`.

The same goes for writing. When writing a `Value::Object`, if the object is empty, it is not written to the output.

This makes a lot of sense for normal gltf objects, however for extensions this poses a problem. Extensions can (and often will) modify the default behaviour if they are present, even if they do not define any of their properties (e.g. their properties are all default values).

The spec defines the `extensions` object like this: `Dictionary object with extension-specific objects.` Strictly speaking, this means all values contained by the `extensions` object should be objects themselves.

I suggest we modify the `ParseExtensionsProperty` and `SerializeExtensionMap` to always serialize the top-level values in the `extensions` object as objects.

This means we will be able to read and subsequently write this, which is currently not possible:
```
"materials": [
    {
        "name": "WHITE",
        "extensions": {
            "VENDOR_material_some_ext": {
            }
        }
    },
```

**Comment by syoyo** [comment]
Thank you for detailed explanation.

I will try to fix it.

> Dictionary object with extension-specific objects

BTW, do you have glTF URL describing this in detail?

**Comment by Selmar** [comment]
There is no direct specification of this, but it's in all of the descriptions for the extensions objects, e.g. [accessor.extensions](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-accessor) in the properties reference.

**Comment by Selmar** [comment]
Scrap that, the `extension` type has a separate description (which says just that, in fact):
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#extension

Schema:
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/extension.schema.json

**Comment by Selmar** [comment]
> For this, I think you can also see `extensionsUsed` and/or `extensionRequired` of root glTF property.

Sure, but if it is a material extension, for example, you also need to know which material.

**Comment by syoyo** [comment]
>  but if it is a material extension, for example, you also need to know which material.

I see.
